# Generated by Django 3.1.4 on 2020-12-25 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=60, null=True)),
                ('last_name', models.CharField(max_length=60, null=True)),
                ('region', models.CharField(choices=[('northeast', 'Northeast'), ('west', 'West'), ('midwest', 'Midwest'), ('canada', 'Canada'), ('southeast', 'Southeast'), ('southwest', 'Southwest')], max_length=60, null=True)),
                ('center', models.CharField(choices=[('philadelphia', 'Philadelphia'), ('robbinsville', 'Robbinsville'), ('edison', 'Edison'), ('cherry_hill', 'Cherry Hill'), ('boston', 'Boston'), ('atlanta', 'Atlanta'), ('houston', 'Houston'), ('chino_hills', 'Chino Hills'), ('chicago', 'Chicago'), ('toronto', 'Toronto')], max_length=60, null=True)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=60, null=True)),
                ('mandal', models.CharField(choices=[('group_2', 'Group 2'), ('group_1', 'Group 1'), ('group_3', 'Group 3'), ('kishore/kishori', 'Kishore/Kishori'), ('group_0', 'Group 0')], max_length=60, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('imageURL', models.URLField(null=True)),
                ('is_selectable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MukhpathItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('english_content', models.CharField(max_length=60)),
                ('gujurati_content', models.CharField(max_length=60)),
                ('transliteration_content', models.CharField(max_length=60)),
                ('audio_url', models.CharField(max_length=60)),
                ('video_url', models.CharField(max_length=60)),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.module')),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PledgedModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('ghanshyam', 'Ghanshyam'), ('mahant', 'Mahant'), ('pramukh', 'Pramukh'), ('yogi', 'Yogi'), ('shastri', 'Shastri')], max_length=60, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.module')),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pledge')),
            ],
        ),
        migrations.CreateModel(
            name='MukhpathItemInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_memorized', models.BooleanField(default=False)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('module_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.moduleinstance')),
                ('mukhpath_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mukhpathitem')),
            ],
        ),
    ]
