# Generated by Django 3.1.4 on 2020-12-20 21:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MukhpathItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('type', models.CharField(choices=[('satsang_diksha', 'Satsang Diksha'), ('swamini_vato', 'Swamini Vato'), ('shlok_sakhi', 'Shlok/Sakhi'), ('kirtan', 'Kirtan'), ('prasang_manan', 'Prasang Manan')], max_length=60)),
                ('english_content', models.CharField(max_length=60)),
                ('gujurati_content', models.CharField(max_length=60)),
                ('transliteration_content', models.CharField(max_length=60)),
                ('audio_url', models.CharField(max_length=60)),
                ('video_url', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='module',
            name='default_mukhpath',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=0),
        ),
        migrations.AddField(
            model_name='module',
            name='finished_mukhpath',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(default=True), null=True, size=0),
        ),
        migrations.AddField(
            model_name='module',
            name='is_selectable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='mukhpath',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=0),
        ),
        migrations.AddField(
            model_name='module',
            name='tier',
            field=models.CharField(choices=[('ghanshyam', 'Ghanshyam'), ('mahant', 'Mahant'), ('pramukh', 'Pramukh'), ('yogi', 'Yogi'), ('shastri', 'Shastri')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('satsang_diksha', 'Satsang Diksha'), ('swamini_vato', 'Swamini Vato'), ('shlok_sakhi', 'Shlok/Sakhi'), ('kirtan', 'Kirtan'), ('prasang_manan', 'Prasang Manan')], max_length=60, null=True),
        ),
    ]
