# Generated by Django 3.1.4 on 2020-12-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('robbinsville', 'Robbinsville'), ('cherry_hill', 'Cherry Hill'), ('edison', 'Edison'), ('philadelphia', 'Philadelphia'), ('atlanta', 'Atlanta'), ('houston', 'Houston'), ('chino_hills', 'Chino Hills'), ('chicago', 'Chicago'), ('toronto', 'Toronto')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('kishore/kishori', 'Kishore/Kishori'), ('group_3', 'Group 3'), ('group_0', 'Group 0'), ('group_2', 'Group 2'), ('group_1', 'Group 1')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('southwest', 'Southwest'), ('west', 'West'), ('midwest', 'Midwest'), ('northeast', 'Northeast'), ('canada', 'Canada'), ('southeast', 'Southeast')], max_length=60, null=True),
        ),
    ]
