# Generated by Django 3.1.4 on 2020-12-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('philadelphia', 'Philadelphia'), ('cherry_hill', 'Cherry Hill'), ('boston', 'Boston'), ('edison', 'Edison'), ('robbinsville', 'Robbinsville'), ('atlanta', 'Atlanta'), ('houston', 'Houston'), ('chino_hills', 'Chino Hills'), ('chicago', 'Chicago'), ('toronto', 'Toronto')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_2', 'Group 2'), ('kishore/kishori', 'Kishore/Kishori'), ('group_1', 'Group 1'), ('group_3', 'Group 3'), ('group_0', 'Group 0')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('northeast', 'Northeast'), ('west', 'West'), ('midwest', 'Midwest'), ('southeast', 'Southeast'), ('canada', 'Canada'), ('southwest', 'Southwest')], max_length=60, null=True),
        ),
    ]
