# Generated by Django 3.1.4 on 2020-12-27 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201225_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_bal_mandal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='is_kishore_mandal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mukhpathitem',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mukhpath_items', to='main.module'),
        ),
        migrations.AlterField(
            model_name='mukhpathiteminstance',
            name='module_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mukhpath_item_instances', to='main.moduleinstance'),
        ),
        migrations.AlterField(
            model_name='pledgedmodule',
            name='pledge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pledged_modules', to='main.pledge'),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('philadelphia', 'Philadelphia'), ('robbinsville', 'Robbinsville'), ('edison', 'Edison'), ('cherry_hill', 'Cherry Hill'), ('boston', 'Boston'), ('atlanta', 'Atlanta'), ('houston', 'Houston'), ('chino_hills', 'Chino Hills'), ('chicago', 'Chicago'), ('toronto', 'Toronto')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('kishore/kishori', 'Kishore/Kishori'), ('group_2', 'Group 2'), ('group_3', 'Group 3'), ('group_0', 'Group 0'), ('group_1', 'Group 1')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('southeast', 'Southeast'), ('west', 'West'), ('southwest', 'Southwest'), ('midwest', 'Midwest'), ('northeast', 'Northeast'), ('canada', 'Canada')], max_length=60, null=True),
        ),
    ]
