# Generated by Django 3.1.4 on 2020-12-20 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201220_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='placeholder',
        ),
        migrations.AddField(
            model_name='pledge',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pledge', to=settings.AUTH_USER_MODEL),
        ),
    ]
