# Generated by Django 3.1.4 on 2020-12-24 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201223_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleinstance',
            name='is_selectable',
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='pledge',
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='tier',
        ),
        migrations.AddField(
            model_name='module',
            name='is_selectable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mukhpathiteminstance',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pledge',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('cherry_hill', 'Cherry Hill'), ('philadelphia', 'Philadelphia'), ('robbinsville', 'Robbinsville'), ('edison', 'Edison'), ('atlanta', 'Atlanta'), ('houston', 'Houston'), ('chino_hills', 'Chino Hills'), ('chicago', 'Chicago'), ('toronto', 'Toronto')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_2', 'Group 2'), ('group_1', 'Group 1'), ('group_0', 'Group 0'), ('kishore/kishori', 'Kishore/Kishori'), ('group_3', 'Group 3')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('northeast', 'Northeast'), ('southwest', 'Southwest'), ('midwest', 'Midwest'), ('west', 'West'), ('canada', 'Canada'), ('southeast', 'Southeast')], max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='PledgedModule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('ghanshyam', 'Ghanshyam'), ('mahant', 'Mahant'), ('pramukh', 'Pramukh'), ('yogi', 'Yogi'), ('shastri', 'Shastri')], max_length=60, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.module')),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pledge')),
            ],
        ),
    ]
