# Generated by Django 3.1.4 on 2020-12-20 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201220_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='default_mukhpath',
        ),
        migrations.RemoveField(
            model_name='module',
            name='finished_mukhpath',
        ),
        migrations.RemoveField(
            model_name='module',
            name='mukhpath',
        ),
        migrations.CreateModel(
            name='MukhpathItemInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_memorized', models.BooleanField(default=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.module')),
                ('mukhpath_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mukhpathitem')),
            ],
        ),
    ]
