# Generated by Django 3.1.4 on 2020-12-27 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201227_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mukhpathitem',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='moduleinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('robbinsville', 'Robbinsville'), ('edison', 'Edison'), ('cherry_hill', 'Cherry Hill'), ('boston', 'Boston'), ('philadelphia', 'Philadelphia'), ('atlanta', 'Atlanta'), ('houston', 'Houston'), ('chino_hills', 'Chino Hills'), ('chicago', 'Chicago'), ('toronto', 'Toronto')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_1', 'Group 1'), ('group_2', 'Group 2'), ('group_3', 'Group 3'), ('group_0', 'Group 0'), ('kishore/kishori', 'Kishore/Kishori')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('west', 'West'), ('northeast', 'Northeast'), ('midwest', 'Midwest'), ('southwest', 'Southwest'), ('canada', 'Canada'), ('southeast', 'Southeast')], max_length=60, null=True),
        ),
    ]
