# Generated by Django 3.1.4 on 2020-12-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201224_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mukhpathitem',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('cherry_hill', 'Cherry Hill'), ('edison', 'Edison'), ('philadelphia', 'Philadelphia'), ('robbinsville', 'Robbinsville'), ('atlanta', 'Atlanta'), ('houston', 'Houston'), ('chino_hills', 'Chino Hills'), ('chicago', 'Chicago'), ('toronto', 'Toronto')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_2', 'Group 2'), ('group_0', 'Group 0'), ('group_3', 'Group 3'), ('kishore/kishori', 'Kishore/Kishori'), ('group_1', 'Group 1')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('southwest', 'Southwest'), ('northeast', 'Northeast'), ('midwest', 'Midwest'), ('southeast', 'Southeast'), ('canada', 'Canada'), ('west', 'West')], max_length=60, null=True),
        ),
    ]
