# Generated by Django 3.1.4 on 2020-12-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201220_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('cherry_hill', 'Cherry Hill'), ('edison', 'Edison'), ('philadelphia', 'Philadelphia'), ('robbinsville', 'Robbinsville')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_0', 'Group 0'), ('group_1', 'Group 1'), ('group_2', 'Group 2'), ('group_3', 'Group 3'), ('kishore_kishori', 'Kishore/Kishori')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('west', 'West'), ('northeast', 'Northeast'), ('southwest', 'Southwest')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='side',
            field=models.CharField(choices=[('i_side', 'I Side'), ('e_side', 'E Side')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('satsang_diksha', 'Satsang Diksha'), ('swamini_vato', 'Swamini Vato'), ('shlok_sakhi', 'Shlok/Sakhi'), ('kirtan', 'Kirtan'), ('prasang_manan', 'Prasang Manan'), ('mahima', 'Mahima'), ('seva', 'Seva'), ('samarpan', 'Samarpan'), ('bhakti', 'bhakti'), ('ahnik', 'ahnik')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='mukhpathitem',
            name='type',
            field=models.CharField(choices=[('satsang_diksha', 'Satsang Diksha'), ('swamini_vato', 'Swamini Vato'), ('shlok_sakhi', 'Shlok/Sakhi'), ('kirtan', 'Kirtan'), ('prasang_manan', 'Prasang Manan'), ('mahima', 'Mahima'), ('seva', 'Seva'), ('samarpan', 'Samarpan'), ('bhakti', 'bhakti'), ('ahnik', 'ahnik')], max_length=60),
        ),
    ]
