# Generated by Django 3.1.4 on 2020-12-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201224_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('philadelphia', 'Philadelphia'), ('robbinsville', 'Robbinsville'), ('cherry_hill', 'Cherry Hill'), ('edison', 'Edison'), ('atlanta', 'Atlanta'), ('houston', 'Houston'), ('chino_hills', 'Chino Hills'), ('chicago', 'Chicago'), ('toronto', 'Toronto')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_3', 'Group 3'), ('kishore/kishori', 'Kishore/Kishori'), ('group_2', 'Group 2'), ('group_1', 'Group 1'), ('group_0', 'Group 0')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('southwest', 'Southwest'), ('southeast', 'Southeast'), ('northeast', 'Northeast'), ('west', 'West'), ('canada', 'Canada'), ('midwest', 'Midwest')], max_length=60, null=True),
        ),
    ]
