# Generated by Django 3.1.4 on 2020-12-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201227_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('robbinsville', 'Robbinsville'), ('philadelphia', 'Philadelphia'), ('cherry_hill', 'Cherry Hill'), ('boston', 'Boston'), ('edison', 'Edison'), ('atlanta', 'Atlanta'), ('houston', 'Houston'), ('chino_hills', 'Chino Hills'), ('chicago', 'Chicago'), ('toronto', 'Toronto')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_2', 'Group 2'), ('group_0', 'Group 0'), ('group_3', 'Group 3'), ('group_1', 'Group 1'), ('kishore/kishori', 'Kishore/Kishori')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('southwest', 'Southwest'), ('canada', 'Canada'), ('midwest', 'Midwest'), ('southeast', 'Southeast'), ('west', 'West'), ('northeast', 'Northeast')], max_length=60, null=True),
        ),
    ]
