# Generated by Django 3.1.4 on 2020-12-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201221_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('satsang_diksha', 'Satsang Diksha'), ('swamini_vato', 'Swamini Vato'), ('shlok_sakhi', 'Shlok/Sakhi'), ('kirtan', 'Kirtan'), ('prasang_manan', 'Prasang Manan'), ('mahima', 'Mahima'), ('seva', 'Seva'), ('samarpan', 'Samarpan'), ('bhakti', 'Bhakti'), ('ahnik', 'Ahnik')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='mukhpathitem',
            name='type',
            field=models.CharField(choices=[('satsang_diksha', 'Satsang Diksha'), ('swamini_vato', 'Swamini Vato'), ('shlok_sakhi', 'Shlok/Sakhi'), ('kirtan', 'Kirtan'), ('prasang_manan', 'Prasang Manan'), ('mahima', 'Mahima'), ('seva', 'Seva'), ('samarpan', 'Samarpan'), ('bhakti', 'Bhakti'), ('ahnik', 'Ahnik')], max_length=60),
        ),
    ]
