# Generated by Django 3.1.4 on 2020-12-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201228_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mukhpathitem',
            old_name='type',
            new_name='mukhpath_type',
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('robbinsville', 'Robbinsville'), ('philadelphia', 'Philadelphia'), ('edison', 'Edison'), ('cherry_hill', 'Cherry Hill'), ('boston', 'Boston'), ('atlanta', 'Atlanta'), ('houston', 'Houston'), ('chino_hills', 'Chino Hills'), ('chicago', 'Chicago'), ('toronto', 'Toronto')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_2', 'Group 2'), ('kishore/kishori', 'Kishore/Kishori'), ('group_3', 'Group 3'), ('group_1', 'Group 1'), ('group_0', 'Group 0')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('southeast', 'Southeast'), ('west', 'West'), ('northeast', 'Northeast'), ('midwest', 'Midwest'), ('canada', 'Canada'), ('southwest', 'Southwest')], max_length=60, null=True),
        ),
    ]
