# Generated by Django 3.1.4 on 2020-12-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201228_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('edison', 'Edison'), ('philadelphia', 'Philadelphia'), ('cherry_hill', 'Cherry Hill'), ('robbinsville', 'Robbinsville'), ('boston', 'Boston'), ('atlanta', 'Atlanta'), ('houston', 'Houston'), ('chino_hills', 'Chino Hills'), ('chicago', 'Chicago'), ('toronto', 'Toronto')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_0', 'Group 0'), ('group_3', 'Group 3'), ('group_1', 'Group 1'), ('group_2', 'Group 2'), ('kishore/kishori', 'Kishore/Kishori')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('canada', 'Canada'), ('southwest', 'Southwest'), ('midwest', 'Midwest'), ('west', 'West'), ('northeast', 'Northeast'), ('southeast', 'Southeast')], max_length=60, null=True),
        ),
    ]
