# Generated by Django 3.1.4 on 2020-12-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201228_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mukhpathitem',
            old_name='mukhpath_type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('lansdale', 'Lansdale'), ('westchester', 'Westchester'), ('warrington', 'Warrington'), ('parsippany', 'Parsippany'), ('philadelphia', 'Philadelphia'), ('northern_virginia', 'Northern Virginia'), ('washington_dc', 'Washington Dc'), ('cherry_hill', 'Cherry Hill'), ('boston', 'Boston'), ('clifton', 'Clifton'), ('syracuse', 'Syracuse'), ('hartford', 'Hartford'), ('roanoke', 'Roanoke'), ('albany_ny', 'Albany Ny'), ('jersey_city', 'Jersey City'), ('scranton', 'Scranton'), ('new_haven', 'New Haven'), ('edison', 'Edison'), ('westborough', 'Westborough'), ('virginia_beach', 'Virginia Beach'), ('new_york', 'New York'), ('allentown', 'Allentown'), ('richmond', 'Richmond'), ('delaware', 'Delaware'), ('long_island', 'Long Island'), ('robbinsville', 'Robbinsville'), ('south_boston', 'South Boston'), ('atlantic_city', 'Atlantic City'), ('harrisburg', 'Harrisburg'), ('springfield', 'Springfield'), ('columbia_tn', 'Columbia Tn'), ('knoxville', 'Knoxville'), ('raleigh', 'Raleigh'), ('calhoun', 'Calhoun'), ('gainesville', 'Gainesville'), ('greensboro', 'Greensboro'), ('huntsville', 'Huntsville'), ('orlando', 'Orlando'), ('melbourne', 'Melbourne'), ('atlanta', 'Atlanta'), ('perry', 'Perry'), ('miami', 'Miami'), ('birmingham', 'Birmingham'), ('columbia_sc', 'Columbia Sc'), ('memphis', 'Memphis'), ('greenville', 'Greenville'), ('tampa', 'Tampa'), ('dothan', 'Dothan'), ('nashville', 'Nashville'), ('albany_ga', 'Albany Ga'), ('montgomery', 'Montgomery'), ('charlotte', 'Charlotte'), ('augusta', 'Augusta'), ('chattanooga', 'Chattanooga'), ('savannah', 'Savannah'), ('jacksonville', 'Jacksonville'), ('orangeburg', 'Orangeburg'), ('florence', 'Florence'), ('dallas', 'Dallas'), ('new_orleans', 'New Orleans'), ('corpus_christi', 'Corpus Christi'), ('clear_lake', 'Clear Lake'), ('houston', 'Houston'), ('austin', 'Austin'), ('san_antonio', 'San Antonio'), ('lubbock', 'Lubbock'), ('beaumont', 'Beaumont'), ('little_rock', 'Little Rock'), ('jackson', 'Jackson'), ('oklahoma_city', 'Oklahoma City'), ('sacramento', 'Sacramento'), ('portland', 'Portland'), ('san_diego', 'San Diego'), ('seattle', 'Seattle'), ('los_angeles', 'Los Angeles'), ('san_francisco', 'San Francisco'), ('salt_lake_city', 'Salt Lake City'), ('san_jose', 'San Jose'), ('phoenix', 'Phoenix'), ('bakersfield', 'Bakersfield'), ('tucson', 'Tucson'), ('fresno', 'Fresno'), ('st_louis', 'St Louis'), ('crystal_lake', 'Crystal Lake'), ('bloomington', 'Bloomington'), ('cleveland', 'Cleveland'), ('cincinnati', 'Cincinnati'), ('kansas_city', 'Kansas City'), ('louisville', 'Louisville'), ('sterling_heights', 'Sterling Heights'), ('detroit', 'Detroit'), ('milwaukee', 'Milwaukee'), ('munster', 'Munster'), ('columbus', 'Columbus'), ('pittsburgh', 'Pittsburgh'), ('evansville', 'Evansville'), ('indianapolis', 'Indianapolis'), ('minneapolis', 'Minneapolis'), ('dayton', 'Dayton'), ('chicago', 'Chicago'), ('calgary', 'Calgary'), ('scarborough', 'Scarborough'), ('toronto', 'Toronto'), ('edmonton', 'Edmonton'), ('cambridge', 'Cambridge'), ('windsor', 'Windsor'), ('winnipeg', 'Winnipeg')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_1', 'Group 1'), ('group_3', 'Group 3'), ('group_2', 'Group 2'), ('kishore/kishori', 'Kishore/Kishori'), ('group_0', 'Group 0')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('midwest', 'Midwest'), ('canada', 'Canada'), ('southwest', 'Southwest'), ('northeast', 'Northeast'), ('west', 'West'), ('southeast', 'Southeast')], max_length=60, null=True),
        ),
    ]
