# Generated by Django 3.1.4 on 2020-12-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201228_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('robbinsville', 'Robbinsville'), ('jersey_city', 'Jersey City'), ('atlantic_city', 'Atlantic City'), ('delaware', 'Delaware'), ('allentown', 'Allentown'), ('washington_dc', 'Washington Dc'), ('scranton', 'Scranton'), ('westborough', 'Westborough'), ('virginia_beach', 'Virginia Beach'), ('springfield', 'Springfield'), ('boston', 'Boston'), ('clifton', 'Clifton'), ('lansdale', 'Lansdale'), ('hartford', 'Hartford'), ('long_island', 'Long Island'), ('albany_ny', 'Albany Ny'), ('parsippany', 'Parsippany'), ('roanoke', 'Roanoke'), ('warrington', 'Warrington'), ('westchester', 'Westchester'), ('new_haven', 'New Haven'), ('new_york', 'New York'), ('harrisburg', 'Harrisburg'), ('philadelphia', 'Philadelphia'), ('cherry_hill', 'Cherry Hill'), ('syracuse', 'Syracuse'), ('northern_virginia', 'Northern Virginia'), ('edison', 'Edison'), ('richmond', 'Richmond'), ('south_boston', 'South Boston'), ('greenville', 'Greenville'), ('huntsville', 'Huntsville'), ('columbia_sc', 'Columbia Sc'), ('florence', 'Florence'), ('chattanooga', 'Chattanooga'), ('memphis', 'Memphis'), ('tampa', 'Tampa'), ('augusta', 'Augusta'), ('dothan', 'Dothan'), ('atlanta', 'Atlanta'), ('calhoun', 'Calhoun'), ('birmingham', 'Birmingham'), ('columbia_tn', 'Columbia Tn'), ('greensboro', 'Greensboro'), ('jacksonville', 'Jacksonville'), ('knoxville', 'Knoxville'), ('orlando', 'Orlando'), ('charlotte', 'Charlotte'), ('miami', 'Miami'), ('albany_ga', 'Albany Ga'), ('montgomery', 'Montgomery'), ('nashville', 'Nashville'), ('raleigh', 'Raleigh'), ('perry', 'Perry'), ('orangeburg', 'Orangeburg'), ('melbourne', 'Melbourne'), ('savannah', 'Savannah'), ('gainesville', 'Gainesville'), ('san_antonio', 'San Antonio'), ('beaumont', 'Beaumont'), ('jackson', 'Jackson'), ('new_orleans', 'New Orleans'), ('lubbock', 'Lubbock'), ('corpus_christi', 'Corpus Christi'), ('clear_lake', 'Clear Lake'), ('houston', 'Houston'), ('little_rock', 'Little Rock'), ('austin', 'Austin'), ('oklahoma_city', 'Oklahoma City'), ('dallas', 'Dallas'), ('phoenix', 'Phoenix'), ('los_angeles', 'Los Angeles'), ('tucson', 'Tucson'), ('portland', 'Portland'), ('san_francisco', 'San Francisco'), ('seattle', 'Seattle'), ('fresno', 'Fresno'), ('bakersfield', 'Bakersfield'), ('sacramento', 'Sacramento'), ('san_diego', 'San Diego'), ('san_jose', 'San Jose'), ('salt_lake_city', 'Salt Lake City'), ('cincinnati', 'Cincinnati'), ('st_louis', 'St Louis'), ('crystal_lake', 'Crystal Lake'), ('sterling_heights', 'Sterling Heights'), ('bloomington', 'Bloomington'), ('dayton', 'Dayton'), ('detroit', 'Detroit'), ('cleveland', 'Cleveland'), ('kansas_city', 'Kansas City'), ('evansville', 'Evansville'), ('columbus', 'Columbus'), ('chicago', 'Chicago'), ('indianapolis', 'Indianapolis'), ('milwaukee', 'Milwaukee'), ('minneapolis', 'Minneapolis'), ('pittsburgh', 'Pittsburgh'), ('munster', 'Munster'), ('louisville', 'Louisville'), ('scarborough', 'Scarborough'), ('windsor', 'Windsor'), ('toronto', 'Toronto'), ('winnipeg', 'Winnipeg'), ('cambridge', 'Cambridge'), ('edmonton', 'Edmonton'), ('calgary', 'Calgary')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_2', 'Group 2'), ('group_3', 'Group 3'), ('kishore/kishori', 'Kishore/Kishori'), ('group_0', 'Group 0'), ('group_1', 'Group 1')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('canada', 'Canada'), ('northeast', 'Northeast'), ('midwest', 'Midwest'), ('southwest', 'Southwest'), ('southeast', 'Southeast'), ('west', 'West')], max_length=60, null=True),
        ),
    ]
