# Generated by Django 3.1.4 on 2021-01-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201228_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('long_island', 'Long Island'), ('delaware', 'Delaware'), ('clifton', 'Clifton'), ('richmond', 'Richmond'), ('downingtown', 'Downingtown'), ('robbinsville', 'Robbinsville'), ('new_york', 'New York'), ('roanoke', 'Roanoke'), ('edison', 'Edison'), ('boston', 'Boston'), ('springfield', 'Springfield'), ('scranton', 'Scranton'), ('parsippany', 'Parsippany'), ('syracuse', 'Syracuse'), ('hilltop', 'Hilltop'), ('jersey_city', 'Jersey City'), ('lansdale', 'Lansdale'), ('washington_dc', 'Washington Dc'), ('westchester', 'Westchester'), ('westborough', 'Westborough'), ('harrisburg', 'Harrisburg'), ('cherry_hill', 'Cherry Hill'), ('northern_virginia', 'Northern Virginia'), ('new_haven', 'New Haven'), ('warrington', 'Warrington'), ('atlantic_city', 'Atlantic City'), ('albany_ny', 'Albany Ny'), ('allentown', 'Allentown'), ('virginia_beach', 'Virginia Beach'), ('hartford', 'Hartford'), ('south_boston', 'South Boston'), ('philadelphia', 'Philadelphia'), ('tampa', 'Tampa'), ('jacksonville', 'Jacksonville'), ('greenville', 'Greenville'), ('raleigh', 'Raleigh'), ('mobile', 'Mobile'), ('perry', 'Perry'), ('dothan', 'Dothan'), ('montgomery', 'Montgomery'), ('nashville', 'Nashville'), ('knoxville', 'Knoxville'), ('savannah', 'Savannah'), ('orangeburg', 'Orangeburg'), ('augusta', 'Augusta'), ('columbia_tn', 'Columbia Tn'), ('melbourne', 'Melbourne'), ('orlando', 'Orlando'), ('columbia_sc', 'Columbia Sc'), ('gainesville', 'Gainesville'), ('memphis', 'Memphis'), ('huntsville', 'Huntsville'), ('albany_ga', 'Albany Ga'), ('birmingham', 'Birmingham'), ('florence', 'Florence'), ('miami', 'Miami'), ('myrtle_beach', 'Myrtle Beach'), ('calhoun', 'Calhoun'), ('greensboro', 'Greensboro'), ('chattanooga', 'Chattanooga'), ('charlotte', 'Charlotte'), ('atlanta', 'Atlanta'), ('beaumont', 'Beaumont'), ('midland', 'Midland'), ('corpus_christi', 'Corpus Christi'), ('dallas', 'Dallas'), ('denver', 'Denver'), ('jackson', 'Jackson'), ('clear_lake', 'Clear Lake'), ('san_antonio', 'San Antonio'), ('oklahoma_city', 'Oklahoma City'), ('houston', 'Houston'), ('austin', 'Austin'), ('lubbock', 'Lubbock'), ('new_orleans', 'New Orleans'), ('little_rock', 'Little Rock'), ('panama', 'Panama'), ('san_francisco', 'San Francisco'), ('los_angeles', 'Los Angeles'), ('fresno', 'Fresno'), ('sacramento', 'Sacramento'), ('san_jose', 'San Jose'), ('seattle', 'Seattle'), ('salt_lake_city', 'Salt Lake City'), ('tucson', 'Tucson'), ('bakersfield', 'Bakersfield'), ('phoenix', 'Phoenix'), ('portland', 'Portland'), ('san_diego', 'San Diego'), ('chicago', 'Chicago'), ('cincinnati', 'Cincinnati'), ('lexington', 'Lexington'), ('columbus', 'Columbus'), ('st_louis', 'St Louis'), ('kalamazoo', 'Kalamazoo'), ('detroit', 'Detroit'), ('kansas_city', 'Kansas City'), ('minneapolis', 'Minneapolis'), ('munster', 'Munster'), ('iowa_city', 'Iowa City'), ('evansville', 'Evansville'), ('crystal_lake', 'Crystal Lake'), ('dayton', 'Dayton'), ('wichita', 'Wichita'), ('louisville', 'Louisville'), ('indianapolis', 'Indianapolis'), ('milwaukee', 'Milwaukee'), ('cleveland', 'Cleveland'), ('bloomington', 'Bloomington'), ('sterling_heights', 'Sterling Heights'), ('pittsburgh', 'Pittsburgh'), ('des_moines', 'Des Moines'), ('fort_mcmurray', 'Fort Mcmurray'), ('montreal', 'Montreal'), ('saskatoon', 'Saskatoon'), ('winnipeg', 'Winnipeg'), ('windsor', 'Windsor'), ('vancouver', 'Vancouver'), ('brandon', 'Brandon'), ('regina', 'Regina'), ('ottawa', 'Ottawa'), ('scarborough', 'Scarborough'), ('red_deer', 'Red Deer'), ('edmonton', 'Edmonton'), ('cambridge', 'Cambridge'), ('calgary', 'Calgary'), ('toronto', 'Toronto')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_0', 'Group 0'), ('kishore/kishori', 'Kishore/Kishori'), ('group_2', 'Group 2'), ('group_1', 'Group 1'), ('group_3', 'Group 3')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('west', 'West'), ('southwest', 'Southwest'), ('northeast', 'Northeast'), ('midwest', 'Midwest'), ('canada', 'Canada'), ('southeast', 'Southeast')], max_length=60, null=True),
        ),
    ]
