# Generated by Django 3.1.4 on 2021-01-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210103_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('clifton', 'Clifton'), ('atlantic_city', 'Atlantic City'), ('northern_virginia', 'Northern Virginia'), ('scranton', 'Scranton'), ('boston', 'Boston'), ('harrisburg', 'Harrisburg'), ('new_haven', 'New Haven'), ('new_york', 'New York'), ('virginia_beach', 'Virginia Beach'), ('south_boston', 'South Boston'), ('roanoke', 'Roanoke'), ('lansdale', 'Lansdale'), ('westchester', 'Westchester'), ('cherry_hill', 'Cherry Hill'), ('westborough', 'Westborough'), ('richmond', 'Richmond'), ('robbinsville', 'Robbinsville'), ('springfield', 'Springfield'), ('philadelphia', 'Philadelphia'), ('jersey_city', 'Jersey City'), ('edison', 'Edison'), ('parsippany', 'Parsippany'), ('delaware', 'Delaware'), ('warrington', 'Warrington'), ('hilltop', 'Hilltop'), ('hartford', 'Hartford'), ('washington_dc', 'Washington Dc'), ('syracuse', 'Syracuse'), ('albany_ny', 'Albany Ny'), ('allentown', 'Allentown'), ('downingtown', 'Downingtown'), ('long_island', 'Long Island'), ('atlanta', 'Atlanta'), ('charlotte', 'Charlotte'), ('nashville', 'Nashville'), ('melbourne', 'Melbourne'), ('jacksonville', 'Jacksonville'), ('albany_ga', 'Albany Ga'), ('miami', 'Miami'), ('chattanooga', 'Chattanooga'), ('greenville', 'Greenville'), ('greensboro', 'Greensboro'), ('columbia_tn', 'Columbia Tn'), ('raleigh', 'Raleigh'), ('memphis', 'Memphis'), ('mobile', 'Mobile'), ('myrtle_beach', 'Myrtle Beach'), ('calhoun', 'Calhoun'), ('tampa', 'Tampa'), ('birmingham', 'Birmingham'), ('knoxville', 'Knoxville'), ('savannah', 'Savannah'), ('augusta', 'Augusta'), ('dothan', 'Dothan'), ('gainesville', 'Gainesville'), ('florence', 'Florence'), ('montgomery', 'Montgomery'), ('orlando', 'Orlando'), ('huntsville', 'Huntsville'), ('perry', 'Perry'), ('orangeburg', 'Orangeburg'), ('columbia_sc', 'Columbia Sc'), ('dallas', 'Dallas'), ('austin', 'Austin'), ('denver', 'Denver'), ('jackson', 'Jackson'), ('corpus_christi', 'Corpus Christi'), ('little_rock', 'Little Rock'), ('midland', 'Midland'), ('clear_lake', 'Clear Lake'), ('panama', 'Panama'), ('new_orleans', 'New Orleans'), ('lubbock', 'Lubbock'), ('beaumont', 'Beaumont'), ('oklahoma_city', 'Oklahoma City'), ('san_antonio', 'San Antonio'), ('houston', 'Houston'), ('los_angeles', 'Los Angeles'), ('phoenix', 'Phoenix'), ('bakersfield', 'Bakersfield'), ('fresno', 'Fresno'), ('salt_lake_city', 'Salt Lake City'), ('san_diego', 'San Diego'), ('sacramento', 'Sacramento'), ('san_jose', 'San Jose'), ('tucson', 'Tucson'), ('seattle', 'Seattle'), ('san_francisco', 'San Francisco'), ('portland', 'Portland'), ('minneapolis', 'Minneapolis'), ('cincinnati', 'Cincinnati'), ('sterling_heights', 'Sterling Heights'), ('crystal_lake', 'Crystal Lake'), ('columbus', 'Columbus'), ('louisville', 'Louisville'), ('st_louis', 'St Louis'), ('bloomington', 'Bloomington'), ('kansas_city', 'Kansas City'), ('evansville', 'Evansville'), ('wichita', 'Wichita'), ('kalamazoo', 'Kalamazoo'), ('des_moines', 'Des Moines'), ('dayton', 'Dayton'), ('chicago', 'Chicago'), ('milwaukee', 'Milwaukee'), ('cleveland', 'Cleveland'), ('iowa_city', 'Iowa City'), ('indianapolis', 'Indianapolis'), ('detroit', 'Detroit'), ('pittsburgh', 'Pittsburgh'), ('lexington', 'Lexington'), ('munster', 'Munster'), ('cambridge', 'Cambridge'), ('toronto', 'Toronto'), ('montreal', 'Montreal'), ('ottawa', 'Ottawa'), ('winnipeg', 'Winnipeg'), ('red_deer', 'Red Deer'), ('vancouver', 'Vancouver'), ('scarborough', 'Scarborough'), ('regina', 'Regina'), ('brandon', 'Brandon'), ('saskatoon', 'Saskatoon'), ('windsor', 'Windsor'), ('edmonton', 'Edmonton'), ('calgary', 'Calgary'), ('fort_mcmurray', 'Fort Mcmurray')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_2', 'Group 2'), ('group_1', 'Group 1'), ('group_0', 'Group 0'), ('kishore/kishori', 'Kishore/Kishori'), ('group_3', 'Group 3')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('canada', 'Canada'), ('midwest', 'Midwest'), ('northeast', 'Northeast'), ('west', 'West'), ('southeast', 'Southeast'), ('southwest', 'Southwest')], max_length=60, null=True),
        ),
    ]
