# Generated by Django 3.1.4 on 2021-01-06 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210103_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='is_bal_mandal',
        ),
        migrations.AlterField(
            model_name='pledgedmodule',
            name='tier',
            field=models.CharField(choices=[('ghanshyam', 'Ghanshyam'), ('mahant', 'Mahant'), ('pramukh', 'Pramukh'), ('yogi', 'Yogi'), ('shastri', 'Shastri'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('parsippany', 'Parsippany'), ('allentown', 'Allentown'), ('atlantic_city', 'Atlantic City'), ('edison', 'Edison'), ('new_york', 'New York'), ('philadelphia', 'Philadelphia'), ('robbinsville', 'Robbinsville'), ('warrington', 'Warrington'), ('richmond', 'Richmond'), ('lansdale', 'Lansdale'), ('south_boston', 'South Boston'), ('clifton', 'Clifton'), ('northern_virginia', 'Northern Virginia'), ('jersey_city', 'Jersey City'), ('springfield', 'Springfield'), ('syracuse', 'Syracuse'), ('new_haven', 'New Haven'), ('harrisburg', 'Harrisburg'), ('scranton', 'Scranton'), ('roanoke', 'Roanoke'), ('downingtown', 'Downingtown'), ('delaware', 'Delaware'), ('washington_dc', 'Washington Dc'), ('long_island', 'Long Island'), ('cherry_hill', 'Cherry Hill'), ('westchester', 'Westchester'), ('albany_ny', 'Albany Ny'), ('hartford', 'Hartford'), ('boston', 'Boston'), ('virginia_beach', 'Virginia Beach'), ('westborough', 'Westborough'), ('hilltop', 'Hilltop'), ('charlotte', 'Charlotte'), ('tampa', 'Tampa'), ('birmingham', 'Birmingham'), ('myrtle_beach', 'Myrtle Beach'), ('jacksonville', 'Jacksonville'), ('gainesville', 'Gainesville'), ('huntsville', 'Huntsville'), ('greenville', 'Greenville'), ('greensboro', 'Greensboro'), ('melbourne', 'Melbourne'), ('orlando', 'Orlando'), ('albany_ga', 'Albany Ga'), ('miami', 'Miami'), ('atlanta', 'Atlanta'), ('savannah', 'Savannah'), ('mobile', 'Mobile'), ('memphis', 'Memphis'), ('dothan', 'Dothan'), ('nashville', 'Nashville'), ('augusta', 'Augusta'), ('columbia_tn', 'Columbia Tn'), ('calhoun', 'Calhoun'), ('knoxville', 'Knoxville'), ('florence', 'Florence'), ('raleigh', 'Raleigh'), ('perry', 'Perry'), ('chattanooga', 'Chattanooga'), ('montgomery', 'Montgomery'), ('columbia_sc', 'Columbia Sc'), ('orangeburg', 'Orangeburg'), ('corpus_christi', 'Corpus Christi'), ('panama', 'Panama'), ('clear_lake', 'Clear Lake'), ('denver', 'Denver'), ('lubbock', 'Lubbock'), ('midland', 'Midland'), ('oklahoma_city', 'Oklahoma City'), ('new_orleans', 'New Orleans'), ('austin', 'Austin'), ('little_rock', 'Little Rock'), ('beaumont', 'Beaumont'), ('dallas', 'Dallas'), ('san_antonio', 'San Antonio'), ('houston', 'Houston'), ('jackson', 'Jackson'), ('portland', 'Portland'), ('san_diego', 'San Diego'), ('bakersfield', 'Bakersfield'), ('phoenix', 'Phoenix'), ('san_francisco', 'San Francisco'), ('fresno', 'Fresno'), ('seattle', 'Seattle'), ('los_angeles', 'Los Angeles'), ('tucson', 'Tucson'), ('sacramento', 'Sacramento'), ('salt_lake_city', 'Salt Lake City'), ('san_jose', 'San Jose'), ('columbus', 'Columbus'), ('cleveland', 'Cleveland'), ('indianapolis', 'Indianapolis'), ('kalamazoo', 'Kalamazoo'), ('kansas_city', 'Kansas City'), ('des_moines', 'Des Moines'), ('dayton', 'Dayton'), ('st_louis', 'St Louis'), ('detroit', 'Detroit'), ('cincinnati', 'Cincinnati'), ('evansville', 'Evansville'), ('milwaukee', 'Milwaukee'), ('louisville', 'Louisville'), ('chicago', 'Chicago'), ('wichita', 'Wichita'), ('pittsburgh', 'Pittsburgh'), ('lexington', 'Lexington'), ('minneapolis', 'Minneapolis'), ('iowa_city', 'Iowa City'), ('munster', 'Munster'), ('crystal_lake', 'Crystal Lake'), ('sterling_heights', 'Sterling Heights'), ('bloomington', 'Bloomington'), ('cambridge', 'Cambridge'), ('saskatoon', 'Saskatoon'), ('regina', 'Regina'), ('fort_mcmurray', 'Fort Mcmurray'), ('brandon', 'Brandon'), ('winnipeg', 'Winnipeg'), ('montreal', 'Montreal'), ('ottawa', 'Ottawa'), ('red_deer', 'Red Deer'), ('toronto', 'Toronto'), ('vancouver', 'Vancouver'), ('scarborough', 'Scarborough'), ('windsor', 'Windsor'), ('edmonton', 'Edmonton'), ('calgary', 'Calgary')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_3', 'Group 3'), ('kishore/kishori', 'Kishore/Kishori'), ('group_2', 'Group 2'), ('group_0', 'Group 0'), ('group_1', 'Group 1')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('west', 'West'), ('midwest', 'Midwest'), ('southeast', 'Southeast'), ('canada', 'Canada'), ('northeast', 'Northeast'), ('southwest', 'Southwest')], max_length=60, null=True),
        ),
    ]
