# Generated by Django 3.1.4 on 2021-01-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210105_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_bal_mandal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('south_boston', 'South Boston'), ('downingtown', 'Downingtown'), ('northern_virginia', 'Northern Virginia'), ('robbinsville', 'Robbinsville'), ('washington_dc', 'Washington Dc'), ('richmond', 'Richmond'), ('springfield', 'Springfield'), ('edison', 'Edison'), ('westborough', 'Westborough'), ('new_haven', 'New Haven'), ('delaware', 'Delaware'), ('allentown', 'Allentown'), ('atlantic_city', 'Atlantic City'), ('harrisburg', 'Harrisburg'), ('cherry_hill', 'Cherry Hill'), ('albany_ny', 'Albany Ny'), ('hartford', 'Hartford'), ('hilltop', 'Hilltop'), ('new_york', 'New York'), ('virginia_beach', 'Virginia Beach'), ('lansdale', 'Lansdale'), ('scranton', 'Scranton'), ('warrington', 'Warrington'), ('philadelphia', 'Philadelphia'), ('parsippany', 'Parsippany'), ('clifton', 'Clifton'), ('boston', 'Boston'), ('jersey_city', 'Jersey City'), ('long_island', 'Long Island'), ('westchester', 'Westchester'), ('roanoke', 'Roanoke'), ('syracuse', 'Syracuse'), ('gainesville', 'Gainesville'), ('jacksonville', 'Jacksonville'), ('raleigh', 'Raleigh'), ('tampa', 'Tampa'), ('montgomery', 'Montgomery'), ('miami', 'Miami'), ('memphis', 'Memphis'), ('melbourne', 'Melbourne'), ('calhoun', 'Calhoun'), ('columbia_tn', 'Columbia Tn'), ('myrtle_beach', 'Myrtle Beach'), ('augusta', 'Augusta'), ('greenville', 'Greenville'), ('chattanooga', 'Chattanooga'), ('mobile', 'Mobile'), ('florence', 'Florence'), ('orangeburg', 'Orangeburg'), ('albany_ga', 'Albany Ga'), ('orlando', 'Orlando'), ('savannah', 'Savannah'), ('dothan', 'Dothan'), ('perry', 'Perry'), ('knoxville', 'Knoxville'), ('atlanta', 'Atlanta'), ('huntsville', 'Huntsville'), ('columbia_sc', 'Columbia Sc'), ('nashville', 'Nashville'), ('greensboro', 'Greensboro'), ('birmingham', 'Birmingham'), ('charlotte', 'Charlotte'), ('lubbock', 'Lubbock'), ('austin', 'Austin'), ('denver', 'Denver'), ('clear_lake', 'Clear Lake'), ('corpus_christi', 'Corpus Christi'), ('midland', 'Midland'), ('dallas', 'Dallas'), ('little_rock', 'Little Rock'), ('new_orleans', 'New Orleans'), ('panama', 'Panama'), ('san_antonio', 'San Antonio'), ('houston', 'Houston'), ('oklahoma_city', 'Oklahoma City'), ('beaumont', 'Beaumont'), ('jackson', 'Jackson'), ('san_francisco', 'San Francisco'), ('sacramento', 'Sacramento'), ('san_diego', 'San Diego'), ('salt_lake_city', 'Salt Lake City'), ('tucson', 'Tucson'), ('san_jose', 'San Jose'), ('los_angeles', 'Los Angeles'), ('bakersfield', 'Bakersfield'), ('fresno', 'Fresno'), ('phoenix', 'Phoenix'), ('seattle', 'Seattle'), ('portland', 'Portland'), ('wichita', 'Wichita'), ('cleveland', 'Cleveland'), ('kansas_city', 'Kansas City'), ('indianapolis', 'Indianapolis'), ('iowa_city', 'Iowa City'), ('chicago', 'Chicago'), ('dayton', 'Dayton'), ('milwaukee', 'Milwaukee'), ('lexington', 'Lexington'), ('columbus', 'Columbus'), ('kalamazoo', 'Kalamazoo'), ('st_louis', 'St Louis'), ('sterling_heights', 'Sterling Heights'), ('des_moines', 'Des Moines'), ('evansville', 'Evansville'), ('crystal_lake', 'Crystal Lake'), ('cincinnati', 'Cincinnati'), ('detroit', 'Detroit'), ('louisville', 'Louisville'), ('bloomington', 'Bloomington'), ('minneapolis', 'Minneapolis'), ('pittsburgh', 'Pittsburgh'), ('munster', 'Munster'), ('regina', 'Regina'), ('windsor', 'Windsor'), ('fort_mcmurray', 'Fort Mcmurray'), ('edmonton', 'Edmonton'), ('ottawa', 'Ottawa'), ('toronto', 'Toronto'), ('brandon', 'Brandon'), ('red_deer', 'Red Deer'), ('winnipeg', 'Winnipeg'), ('scarborough', 'Scarborough'), ('calgary', 'Calgary'), ('vancouver', 'Vancouver'), ('montreal', 'Montreal'), ('cambridge', 'Cambridge'), ('saskatoon', 'Saskatoon')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_1', 'Group 1'), ('group_0', 'Group 0'), ('kishore/kishori', 'Kishore/Kishori'), ('group_3', 'Group 3'), ('group_2', 'Group 2')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('west', 'West'), ('northeast', 'Northeast'), ('canada', 'Canada'), ('midwest', 'Midwest'), ('southeast', 'Southeast'), ('southwest', 'Southwest')], max_length=60, null=True),
        ),
    ]
