# Generated by Django 3.1.4 on 2021-01-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210110_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mukhpathitem',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='mukhpathitem',
            name='audio_url',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mukhpathitem',
            name='english_content',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='mukhpathitem',
            name='gujurati_content',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='mukhpathitem',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mukhpathitem',
            name='transliteration_content',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('downingtown', 'Downingtown'), ('westborough', 'Westborough'), ('virginia_beach', 'Virginia Beach'), ('richmond', 'Richmond'), ('albany_ny', 'Albany Ny'), ('parsippany', 'Parsippany'), ('jersey_city', 'Jersey City'), ('northern_virginia', 'Northern Virginia'), ('atlantic_city', 'Atlantic City'), ('hartford', 'Hartford'), ('syracuse', 'Syracuse'), ('cherry_hill', 'Cherry Hill'), ('edison', 'Edison'), ('harrisburg', 'Harrisburg'), ('new_haven', 'New Haven'), ('scranton', 'Scranton'), ('hilltop', 'Hilltop'), ('south_boston', 'South Boston'), ('roanoke', 'Roanoke'), ('warrington', 'Warrington'), ('washington_dc', 'Washington Dc'), ('philadelphia', 'Philadelphia'), ('delaware', 'Delaware'), ('springfield', 'Springfield'), ('long_island', 'Long Island'), ('clifton', 'Clifton'), ('lansdale', 'Lansdale'), ('robbinsville', 'Robbinsville'), ('westchester', 'Westchester'), ('boston', 'Boston'), ('new_york', 'New York'), ('allentown', 'Allentown'), ('knoxville', 'Knoxville'), ('birmingham', 'Birmingham'), ('gainesville', 'Gainesville'), ('greenville', 'Greenville'), ('albany_ga', 'Albany Ga'), ('orangeburg', 'Orangeburg'), ('florence', 'Florence'), ('myrtle_beach', 'Myrtle Beach'), ('perry', 'Perry'), ('montgomery', 'Montgomery'), ('miami', 'Miami'), ('jacksonville', 'Jacksonville'), ('chattanooga', 'Chattanooga'), ('columbia_sc', 'Columbia Sc'), ('dothan', 'Dothan'), ('mobile', 'Mobile'), ('nashville', 'Nashville'), ('charlotte', 'Charlotte'), ('savannah', 'Savannah'), ('raleigh', 'Raleigh'), ('huntsville', 'Huntsville'), ('melbourne', 'Melbourne'), ('tampa', 'Tampa'), ('calhoun', 'Calhoun'), ('atlanta', 'Atlanta'), ('orlando', 'Orlando'), ('columbia_tn', 'Columbia Tn'), ('greensboro', 'Greensboro'), ('memphis', 'Memphis'), ('augusta', 'Augusta'), ('beaumont', 'Beaumont'), ('dallas', 'Dallas'), ('corpus_christi', 'Corpus Christi'), ('midland', 'Midland'), ('new_orleans', 'New Orleans'), ('panama', 'Panama'), ('denver', 'Denver'), ('oklahoma_city', 'Oklahoma City'), ('san_antonio', 'San Antonio'), ('lubbock', 'Lubbock'), ('austin', 'Austin'), ('houston', 'Houston'), ('little_rock', 'Little Rock'), ('jackson', 'Jackson'), ('clear_lake', 'Clear Lake'), ('portland', 'Portland'), ('los_angeles', 'Los Angeles'), ('san_jose', 'San Jose'), ('san_diego', 'San Diego'), ('bakersfield', 'Bakersfield'), ('phoenix', 'Phoenix'), ('salt_lake_city', 'Salt Lake City'), ('tucson', 'Tucson'), ('fresno', 'Fresno'), ('san_francisco', 'San Francisco'), ('seattle', 'Seattle'), ('sacramento', 'Sacramento'), ('st_louis', 'St Louis'), ('cincinnati', 'Cincinnati'), ('detroit', 'Detroit'), ('lexington', 'Lexington'), ('cleveland', 'Cleveland'), ('bloomington', 'Bloomington'), ('louisville', 'Louisville'), ('sterling_heights', 'Sterling Heights'), ('columbus', 'Columbus'), ('pittsburgh', 'Pittsburgh'), ('iowa_city', 'Iowa City'), ('wichita', 'Wichita'), ('dayton', 'Dayton'), ('des_moines', 'Des Moines'), ('minneapolis', 'Minneapolis'), ('chicago', 'Chicago'), ('kalamazoo', 'Kalamazoo'), ('indianapolis', 'Indianapolis'), ('crystal_lake', 'Crystal Lake'), ('munster', 'Munster'), ('kansas_city', 'Kansas City'), ('milwaukee', 'Milwaukee'), ('evansville', 'Evansville'), ('brandon', 'Brandon'), ('cambridge', 'Cambridge'), ('red_deer', 'Red Deer'), ('regina', 'Regina'), ('saskatoon', 'Saskatoon'), ('windsor', 'Windsor'), ('fort_mcmurray', 'Fort Mcmurray'), ('calgary', 'Calgary'), ('toronto', 'Toronto'), ('vancouver', 'Vancouver'), ('ottawa', 'Ottawa'), ('winnipeg', 'Winnipeg'), ('scarborough', 'Scarborough'), ('edmonton', 'Edmonton'), ('montreal', 'Montreal')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('kishore/kishori', 'Kishore/Kishori'), ('group_2', 'Group 2'), ('group_1', 'Group 1'), ('group_0', 'Group 0'), ('group_3', 'Group 3')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('southeast', 'Southeast'), ('west', 'West'), ('northeast', 'Northeast'), ('canada', 'Canada'), ('southwest', 'Southwest'), ('midwest', 'Midwest')], max_length=60, null=True),
        ),
    ]
