# Generated by Django 3.1.4 on 2021-01-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210110_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mukhpathitem',
            name='type',
        ),
        migrations.AddField(
            model_name='mukhpathitem',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mukhpathitem',
            name='value',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('syracuse', 'Syracuse'), ('northern_virginia', 'Northern Virginia'), ('harrisburg', 'Harrisburg'), ('westchester', 'Westchester'), ('new_york', 'New York'), ('roanoke', 'Roanoke'), ('warrington', 'Warrington'), ('albany_ny', 'Albany Ny'), ('cherry_hill', 'Cherry Hill'), ('boston', 'Boston'), ('hartford', 'Hartford'), ('downingtown', 'Downingtown'), ('lansdale', 'Lansdale'), ('philadelphia', 'Philadelphia'), ('springfield', 'Springfield'), ('edison', 'Edison'), ('hilltop', 'Hilltop'), ('new_haven', 'New Haven'), ('scranton', 'Scranton'), ('virginia_beach', 'Virginia Beach'), ('long_island', 'Long Island'), ('washington_dc', 'Washington Dc'), ('allentown', 'Allentown'), ('delaware', 'Delaware'), ('robbinsville', 'Robbinsville'), ('south_boston', 'South Boston'), ('jersey_city', 'Jersey City'), ('richmond', 'Richmond'), ('westborough', 'Westborough'), ('parsippany', 'Parsippany'), ('clifton', 'Clifton'), ('atlantic_city', 'Atlantic City'), ('nashville', 'Nashville'), ('memphis', 'Memphis'), ('chattanooga', 'Chattanooga'), ('perry', 'Perry'), ('columbia_tn', 'Columbia Tn'), ('augusta', 'Augusta'), ('calhoun', 'Calhoun'), ('orangeburg', 'Orangeburg'), ('tampa', 'Tampa'), ('albany_ga', 'Albany Ga'), ('melbourne', 'Melbourne'), ('myrtle_beach', 'Myrtle Beach'), ('greensboro', 'Greensboro'), ('savannah', 'Savannah'), ('atlanta', 'Atlanta'), ('florence', 'Florence'), ('charlotte', 'Charlotte'), ('orlando', 'Orlando'), ('jacksonville', 'Jacksonville'), ('mobile', 'Mobile'), ('dothan', 'Dothan'), ('raleigh', 'Raleigh'), ('huntsville', 'Huntsville'), ('miami', 'Miami'), ('montgomery', 'Montgomery'), ('greenville', 'Greenville'), ('birmingham', 'Birmingham'), ('gainesville', 'Gainesville'), ('knoxville', 'Knoxville'), ('columbia_sc', 'Columbia Sc'), ('beaumont', 'Beaumont'), ('corpus_christi', 'Corpus Christi'), ('oklahoma_city', 'Oklahoma City'), ('houston', 'Houston'), ('dallas', 'Dallas'), ('denver', 'Denver'), ('clear_lake', 'Clear Lake'), ('new_orleans', 'New Orleans'), ('austin', 'Austin'), ('midland', 'Midland'), ('panama', 'Panama'), ('jackson', 'Jackson'), ('san_antonio', 'San Antonio'), ('little_rock', 'Little Rock'), ('lubbock', 'Lubbock'), ('san_francisco', 'San Francisco'), ('fresno', 'Fresno'), ('bakersfield', 'Bakersfield'), ('phoenix', 'Phoenix'), ('salt_lake_city', 'Salt Lake City'), ('san_jose', 'San Jose'), ('seattle', 'Seattle'), ('los_angeles', 'Los Angeles'), ('tucson', 'Tucson'), ('portland', 'Portland'), ('sacramento', 'Sacramento'), ('san_diego', 'San Diego'), ('cincinnati', 'Cincinnati'), ('crystal_lake', 'Crystal Lake'), ('louisville', 'Louisville'), ('st_louis', 'St Louis'), ('milwaukee', 'Milwaukee'), ('minneapolis', 'Minneapolis'), ('iowa_city', 'Iowa City'), ('kalamazoo', 'Kalamazoo'), ('columbus', 'Columbus'), ('chicago', 'Chicago'), ('bloomington', 'Bloomington'), ('des_moines', 'Des Moines'), ('wichita', 'Wichita'), ('indianapolis', 'Indianapolis'), ('pittsburgh', 'Pittsburgh'), ('sterling_heights', 'Sterling Heights'), ('detroit', 'Detroit'), ('dayton', 'Dayton'), ('lexington', 'Lexington'), ('munster', 'Munster'), ('cleveland', 'Cleveland'), ('evansville', 'Evansville'), ('kansas_city', 'Kansas City'), ('fort_mcmurray', 'Fort Mcmurray'), ('vancouver', 'Vancouver'), ('ottawa', 'Ottawa'), ('toronto', 'Toronto'), ('calgary', 'Calgary'), ('saskatoon', 'Saskatoon'), ('winnipeg', 'Winnipeg'), ('cambridge', 'Cambridge'), ('regina', 'Regina'), ('scarborough', 'Scarborough'), ('montreal', 'Montreal'), ('edmonton', 'Edmonton'), ('windsor', 'Windsor'), ('red_deer', 'Red Deer'), ('brandon', 'Brandon')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_3', 'Group 3'), ('group_2', 'Group 2'), ('kishore/kishori', 'Kishore/Kishori'), ('group_0', 'Group 0'), ('group_1', 'Group 1')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('northeast', 'Northeast'), ('midwest', 'Midwest'), ('west', 'West'), ('southwest', 'Southwest'), ('canada', 'Canada'), ('southeast', 'Southeast')], max_length=60, null=True),
        ),
    ]
