# Generated by Django 3.1.4 on 2021-01-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210112_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='module',
            name='image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('robbinsville', 'Robbinsville'), ('cherry_hill', 'Cherry Hill'), ('warrington', 'Warrington'), ('richmond', 'Richmond'), ('new_york', 'New York'), ('jersey_city', 'Jersey City'), ('westchester', 'Westchester'), ('long_island', 'Long Island'), ('allentown', 'Allentown'), ('albany_ny', 'Albany Ny'), ('springfield', 'Springfield'), ('delaware', 'Delaware'), ('parsippany', 'Parsippany'), ('hartford', 'Hartford'), ('atlantic_city', 'Atlantic City'), ('harrisburg', 'Harrisburg'), ('downingtown', 'Downingtown'), ('edison', 'Edison'), ('new_haven', 'New Haven'), ('roanoke', 'Roanoke'), ('northern_virginia', 'Northern Virginia'), ('philadelphia', 'Philadelphia'), ('lansdale', 'Lansdale'), ('scranton', 'Scranton'), ('syracuse', 'Syracuse'), ('virginia_beach', 'Virginia Beach'), ('boston', 'Boston'), ('washington_dc', 'Washington Dc'), ('westborough', 'Westborough'), ('south_boston', 'South Boston'), ('hilltop', 'Hilltop'), ('clifton', 'Clifton'), ('tampa', 'Tampa'), ('greenville', 'Greenville'), ('gainesville', 'Gainesville'), ('columbia_sc', 'Columbia Sc'), ('birmingham', 'Birmingham'), ('orlando', 'Orlando'), ('savannah', 'Savannah'), ('jacksonville', 'Jacksonville'), ('chattanooga', 'Chattanooga'), ('dothan', 'Dothan'), ('atlanta', 'Atlanta'), ('mobile', 'Mobile'), ('huntsville', 'Huntsville'), ('greensboro', 'Greensboro'), ('perry', 'Perry'), ('knoxville', 'Knoxville'), ('raleigh', 'Raleigh'), ('albany_ga', 'Albany Ga'), ('myrtle_beach', 'Myrtle Beach'), ('florence', 'Florence'), ('montgomery', 'Montgomery'), ('miami', 'Miami'), ('columbia_tn', 'Columbia Tn'), ('melbourne', 'Melbourne'), ('charlotte', 'Charlotte'), ('nashville', 'Nashville'), ('calhoun', 'Calhoun'), ('orangeburg', 'Orangeburg'), ('memphis', 'Memphis'), ('augusta', 'Augusta'), ('jackson', 'Jackson'), ('denver', 'Denver'), ('corpus_christi', 'Corpus Christi'), ('dallas', 'Dallas'), ('san_antonio', 'San Antonio'), ('little_rock', 'Little Rock'), ('austin', 'Austin'), ('houston', 'Houston'), ('oklahoma_city', 'Oklahoma City'), ('beaumont', 'Beaumont'), ('new_orleans', 'New Orleans'), ('lubbock', 'Lubbock'), ('clear_lake', 'Clear Lake'), ('panama', 'Panama'), ('midland', 'Midland'), ('fresno', 'Fresno'), ('tucson', 'Tucson'), ('salt_lake_city', 'Salt Lake City'), ('san_francisco', 'San Francisco'), ('los_angeles', 'Los Angeles'), ('sacramento', 'Sacramento'), ('seattle', 'Seattle'), ('san_jose', 'San Jose'), ('portland', 'Portland'), ('bakersfield', 'Bakersfield'), ('phoenix', 'Phoenix'), ('san_diego', 'San Diego'), ('cleveland', 'Cleveland'), ('dayton', 'Dayton'), ('iowa_city', 'Iowa City'), ('sterling_heights', 'Sterling Heights'), ('st_louis', 'St Louis'), ('kalamazoo', 'Kalamazoo'), ('indianapolis', 'Indianapolis'), ('lexington', 'Lexington'), ('cincinnati', 'Cincinnati'), ('wichita', 'Wichita'), ('columbus', 'Columbus'), ('crystal_lake', 'Crystal Lake'), ('minneapolis', 'Minneapolis'), ('munster', 'Munster'), ('milwaukee', 'Milwaukee'), ('detroit', 'Detroit'), ('kansas_city', 'Kansas City'), ('louisville', 'Louisville'), ('bloomington', 'Bloomington'), ('pittsburgh', 'Pittsburgh'), ('evansville', 'Evansville'), ('chicago', 'Chicago'), ('des_moines', 'Des Moines'), ('winnipeg', 'Winnipeg'), ('calgary', 'Calgary'), ('regina', 'Regina'), ('saskatoon', 'Saskatoon'), ('toronto', 'Toronto'), ('cambridge', 'Cambridge'), ('montreal', 'Montreal'), ('edmonton', 'Edmonton'), ('red_deer', 'Red Deer'), ('windsor', 'Windsor'), ('vancouver', 'Vancouver'), ('ottawa', 'Ottawa'), ('fort_mcmurray', 'Fort Mcmurray'), ('brandon', 'Brandon'), ('scarborough', 'Scarborough')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_2', 'Group 2'), ('group_0', 'Group 0'), ('kishore/kishori', 'Kishore/Kishori'), ('group_3', 'Group 3'), ('group_1', 'Group 1')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('midwest', 'Midwest'), ('canada', 'Canada'), ('northeast', 'Northeast'), ('southeast', 'Southeast'), ('southwest', 'Southwest'), ('west', 'West')], max_length=60, null=True),
        ),
    ]
