# Generated by Django 3.1.4 on 2021-01-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210115_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='mukhpathitem',
            name='index',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('westborough', 'Westborough'), ('hilltop', 'Hilltop'), ('new_york', 'New York'), ('new_haven', 'New Haven'), ('hartford', 'Hartford'), ('harrisburg', 'Harrisburg'), ('atlantic_city', 'Atlantic City'), ('virginia_beach', 'Virginia Beach'), ('delaware', 'Delaware'), ('jersey_city', 'Jersey City'), ('parsippany', 'Parsippany'), ('cherry_hill', 'Cherry Hill'), ('downingtown', 'Downingtown'), ('westchester', 'Westchester'), ('roanoke', 'Roanoke'), ('allentown', 'Allentown'), ('clifton', 'Clifton'), ('scranton', 'Scranton'), ('albany_ny', 'Albany Ny'), ('edison', 'Edison'), ('northern_virginia', 'Northern Virginia'), ('richmond', 'Richmond'), ('boston', 'Boston'), ('lansdale', 'Lansdale'), ('springfield', 'Springfield'), ('syracuse', 'Syracuse'), ('philadelphia', 'Philadelphia'), ('south_boston', 'South Boston'), ('warrington', 'Warrington'), ('long_island', 'Long Island'), ('robbinsville', 'Robbinsville'), ('washington_dc', 'Washington Dc'), ('birmingham', 'Birmingham'), ('tampa', 'Tampa'), ('chattanooga', 'Chattanooga'), ('jacksonville', 'Jacksonville'), ('greenville', 'Greenville'), ('knoxville', 'Knoxville'), ('raleigh', 'Raleigh'), ('atlanta', 'Atlanta'), ('columbia_sc', 'Columbia Sc'), ('gainesville', 'Gainesville'), ('columbia_tn', 'Columbia Tn'), ('mobile', 'Mobile'), ('memphis', 'Memphis'), ('montgomery', 'Montgomery'), ('orangeburg', 'Orangeburg'), ('calhoun', 'Calhoun'), ('miami', 'Miami'), ('huntsville', 'Huntsville'), ('nashville', 'Nashville'), ('savannah', 'Savannah'), ('augusta', 'Augusta'), ('albany_ga', 'Albany Ga'), ('dothan', 'Dothan'), ('orlando', 'Orlando'), ('florence', 'Florence'), ('perry', 'Perry'), ('greensboro', 'Greensboro'), ('charlotte', 'Charlotte'), ('myrtle_beach', 'Myrtle Beach'), ('melbourne', 'Melbourne'), ('little_rock', 'Little Rock'), ('clear_lake', 'Clear Lake'), ('jackson', 'Jackson'), ('lubbock', 'Lubbock'), ('corpus_christi', 'Corpus Christi'), ('midland', 'Midland'), ('houston', 'Houston'), ('panama', 'Panama'), ('new_orleans', 'New Orleans'), ('san_antonio', 'San Antonio'), ('dallas', 'Dallas'), ('oklahoma_city', 'Oklahoma City'), ('austin', 'Austin'), ('beaumont', 'Beaumont'), ('denver', 'Denver'), ('sacramento', 'Sacramento'), ('san_francisco', 'San Francisco'), ('seattle', 'Seattle'), ('bakersfield', 'Bakersfield'), ('phoenix', 'Phoenix'), ('tucson', 'Tucson'), ('fresno', 'Fresno'), ('portland', 'Portland'), ('los_angeles', 'Los Angeles'), ('san_jose', 'San Jose'), ('salt_lake_city', 'Salt Lake City'), ('san_diego', 'San Diego'), ('cleveland', 'Cleveland'), ('louisville', 'Louisville'), ('lexington', 'Lexington'), ('munster', 'Munster'), ('wichita', 'Wichita'), ('st_louis', 'St Louis'), ('pittsburgh', 'Pittsburgh'), ('minneapolis', 'Minneapolis'), ('columbus', 'Columbus'), ('detroit', 'Detroit'), ('chicago', 'Chicago'), ('dayton', 'Dayton'), ('crystal_lake', 'Crystal Lake'), ('indianapolis', 'Indianapolis'), ('kalamazoo', 'Kalamazoo'), ('kansas_city', 'Kansas City'), ('evansville', 'Evansville'), ('sterling_heights', 'Sterling Heights'), ('des_moines', 'Des Moines'), ('milwaukee', 'Milwaukee'), ('iowa_city', 'Iowa City'), ('bloomington', 'Bloomington'), ('cincinnati', 'Cincinnati'), ('calgary', 'Calgary'), ('winnipeg', 'Winnipeg'), ('saskatoon', 'Saskatoon'), ('toronto', 'Toronto'), ('montreal', 'Montreal'), ('brandon', 'Brandon'), ('red_deer', 'Red Deer'), ('cambridge', 'Cambridge'), ('regina', 'Regina'), ('scarborough', 'Scarborough'), ('fort_mcmurray', 'Fort Mcmurray'), ('vancouver', 'Vancouver'), ('edmonton', 'Edmonton'), ('ottawa', 'Ottawa'), ('windsor', 'Windsor')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_2', 'Group 2'), ('group_1', 'Group 1'), ('kishore/kishori', 'Kishore/Kishori'), ('group_3', 'Group 3'), ('group_0', 'Group 0')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('northeast', 'Northeast'), ('southwest', 'Southwest'), ('west', 'West'), ('canada', 'Canada'), ('southeast', 'Southeast'), ('midwest', 'Midwest')], max_length=60, null=True),
        ),
    ]
