# Generated by Django 3.1.5 on 2021-01-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210115_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('harrisburg', 'Harrisburg'), ('clifton', 'Clifton'), ('philadelphia', 'Philadelphia'), ('allentown', 'Allentown'), ('virginia_beach', 'Virginia Beach'), ('edison', 'Edison'), ('westborough', 'Westborough'), ('new_york', 'New York'), ('scranton', 'Scranton'), ('atlantic_city', 'Atlantic City'), ('new_haven', 'New Haven'), ('richmond', 'Richmond'), ('boston', 'Boston'), ('long_island', 'Long Island'), ('cherry_hill', 'Cherry Hill'), ('roanoke', 'Roanoke'), ('downingtown', 'Downingtown'), ('northern_virginia', 'Northern Virginia'), ('hartford', 'Hartford'), ('robbinsville', 'Robbinsville'), ('albany_ny', 'Albany NY'), ('south_boston', 'South Boston'), ('warrington', 'Warrington'), ('washington_dc', 'Washington DC'), ('hilltop', 'Hilltop'), ('springfield', 'Springfield'), ('lansdale', 'Lansdale'), ('westchester', 'Westchester'), ('parsippany', 'Parsippany'), ('jersey_city', 'Jersey City'), ('delaware', 'Delaware'), ('syracuse', 'Syracuse'), ('jacksonville', 'Jacksonville'), ('melbourne', 'Melbourne'), ('miami', 'Miami'), ('calhoun', 'Calhoun'), ('myrtle_beach', 'Myrtle Beach'), ('columbia_tn', 'Columbia TN'), ('mobile', 'Mobile'), ('montgomery', 'Montgomery'), ('greenville', 'Greenville'), ('savannah', 'Savannah'), ('florence', 'Florence'), ('chattanooga', 'Chattanooga'), ('knoxville', 'Knoxville'), ('orlando', 'Orlando'), ('huntsville', 'Huntsville'), ('tampa', 'Tampa'), ('atlanta', 'Atlanta'), ('charlotte', 'Charlotte'), ('dothan', 'Dothan'), ('orangeburg', 'Orangeburg'), ('albany_ga', 'Albany GA'), ('greensboro', 'Greensboro'), ('birmingham', 'Birmingham'), ('nashville', 'Nashville'), ('perry', 'Perry'), ('raleigh', 'Raleigh'), ('columbia_sc', 'Columbia SC'), ('gainesville', 'Gainesville'), ('memphis', 'Memphis'), ('augusta', 'Augusta'), ('corpus_christi', 'Corpus Christi'), ('denver', 'Denver'), ('houston', 'Houston'), ('beaumont', 'Beaumont'), ('clear_lake', 'Clear Lake'), ('jackson', 'Jackson'), ('panama', 'Panama'), ('midland', 'Midland'), ('little_rock', 'Little Rock'), ('new_orleans', 'New Orleans'), ('oklahoma_city', 'Oklahoma City'), ('san_antonio', 'San Antonio'), ('lubbock', 'Lubbock'), ('austin', 'Austin'), ('dallas', 'Dallas'), ('los_angeles', 'Los Angeles'), ('san_jose', 'San Jose'), ('phoenix', 'Phoenix'), ('san_francisco', 'San Francisco'), ('sacramento', 'Sacramento'), ('portland', 'Portland'), ('seattle', 'Seattle'), ('tucson', 'Tucson'), ('bakersfield', 'Bakersfield'), ('fresno', 'Fresno'), ('san_diego', 'San Diego'), ('salt_lake_city', 'Salt Lake'), ('columbus', 'Columbus'), ('munster', 'Munster'), ('wichita', 'Wichita'), ('dayton', 'Dayton'), ('indianapolis', 'Indianapolis'), ('chicago', 'Chicago'), ('cleveland', 'Cleveland'), ('detroit', 'Detroit'), ('des_moines', 'Des Moines'), ('iowa_city', 'Iowa City'), ('bloomington', 'Bloomington'), ('kansas_city', 'Kansas City'), ('milwaukee', 'Milwaukee'), ('lexington', 'Lexington'), ('cincinnati', 'Cincinnati'), ('crystal_lake', 'Crystal Lake'), ('pittsburgh', 'Pittsburgh'), ('kalamazoo', 'Kalamazoo'), ('sterling_heights', 'Sterling Heights'), ('st_louis', 'St Louis'), ('evansville', 'Evansville'), ('minneapolis', 'Minneapolis'), ('louisville', 'Louisville'), ('scarborough', 'Scarborough'), ('calgary', 'Calgary'), ('cambridge', 'Cambridge'), ('edmonton', 'Edmonton'), ('red_deer', 'Red Deer'), ('toronto', 'Toronto'), ('winnipeg', 'Winnipeg'), ('vancouver', 'Vancouver'), ('brandon', 'Brandon'), ('regina', 'Regina'), ('saskatoon', 'Saskatoon'), ('windsor', 'Windsor'), ('fort_mcmurray', 'Fort Mcmurray'), ('montreal', 'Montreal'), ('ottawa', 'Ottawa')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('kishore/kishori', 'Kishore/Kishori'), ('group_3', 'Group 3'), ('group_0', 'Group 0'), ('group_2', 'Group 2'), ('group_1', 'Group 1')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('southeast', 'Southeast'), ('midwest', 'Midwest'), ('canada', 'Canada'), ('southwest', 'Southwest'), ('west', 'West'), ('northeast', 'Northeast')], max_length=60, null=True),
        ),
    ]
