# Generated by Django 3.1.4 on 2021-01-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210115_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='is_selectable',
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('westborough', 'Westborough'), ('allentown', 'Allentown'), ('downingtown', 'Downingtown'), ('long_island', 'Long Island'), ('richmond', 'Richmond'), ('south_boston', 'South Boston'), ('boston', 'Boston'), ('new_haven', 'New Haven'), ('robbinsville', 'Robbinsville'), ('syracuse', 'Syracuse'), ('springfield', 'Springfield'), ('harrisburg', 'Harrisburg'), ('cherry_hill', 'Cherry Hill'), ('new_york', 'New York'), ('northern_virginia', 'Northern Virginia'), ('parsippany', 'Parsippany'), ('edison', 'Edison'), ('hilltop', 'Hilltop'), ('westchester', 'Westchester'), ('virginia_beach', 'Virginia Beach'), ('atlantic_city', 'Atlantic City'), ('lansdale', 'Lansdale'), ('delaware', 'Delaware'), ('scranton', 'Scranton'), ('jersey_city', 'Jersey City'), ('roanoke', 'Roanoke'), ('clifton', 'Clifton'), ('washington_dc', 'Washington Dc'), ('hartford', 'Hartford'), ('albany_ny', 'Albany Ny'), ('warrington', 'Warrington'), ('philadelphia', 'Philadelphia'), ('perry', 'Perry'), ('nashville', 'Nashville'), ('albany_ga', 'Albany Ga'), ('gainesville', 'Gainesville'), ('miami', 'Miami'), ('orangeburg', 'Orangeburg'), ('greenville', 'Greenville'), ('raleigh', 'Raleigh'), ('memphis', 'Memphis'), ('atlanta', 'Atlanta'), ('florence', 'Florence'), ('savannah', 'Savannah'), ('calhoun', 'Calhoun'), ('myrtle_beach', 'Myrtle Beach'), ('tampa', 'Tampa'), ('chattanooga', 'Chattanooga'), ('birmingham', 'Birmingham'), ('huntsville', 'Huntsville'), ('charlotte', 'Charlotte'), ('knoxville', 'Knoxville'), ('augusta', 'Augusta'), ('orlando', 'Orlando'), ('melbourne', 'Melbourne'), ('columbia_tn', 'Columbia Tn'), ('columbia_sc', 'Columbia Sc'), ('montgomery', 'Montgomery'), ('dothan', 'Dothan'), ('mobile', 'Mobile'), ('greensboro', 'Greensboro'), ('jacksonville', 'Jacksonville'), ('little_rock', 'Little Rock'), ('san_antonio', 'San Antonio'), ('panama', 'Panama'), ('dallas', 'Dallas'), ('austin', 'Austin'), ('lubbock', 'Lubbock'), ('houston', 'Houston'), ('midland', 'Midland'), ('new_orleans', 'New Orleans'), ('clear_lake', 'Clear Lake'), ('corpus_christi', 'Corpus Christi'), ('beaumont', 'Beaumont'), ('oklahoma_city', 'Oklahoma City'), ('jackson', 'Jackson'), ('denver', 'Denver'), ('salt_lake_city', 'Salt Lake City'), ('san_jose', 'San Jose'), ('los_angeles', 'Los Angeles'), ('phoenix', 'Phoenix'), ('portland', 'Portland'), ('fresno', 'Fresno'), ('san_diego', 'San Diego'), ('san_francisco', 'San Francisco'), ('sacramento', 'Sacramento'), ('bakersfield', 'Bakersfield'), ('tucson', 'Tucson'), ('seattle', 'Seattle'), ('munster', 'Munster'), ('sterling_heights', 'Sterling Heights'), ('indianapolis', 'Indianapolis'), ('chicago', 'Chicago'), ('lexington', 'Lexington'), ('crystal_lake', 'Crystal Lake'), ('columbus', 'Columbus'), ('louisville', 'Louisville'), ('st_louis', 'St Louis'), ('kalamazoo', 'Kalamazoo'), ('minneapolis', 'Minneapolis'), ('bloomington', 'Bloomington'), ('kansas_city', 'Kansas City'), ('evansville', 'Evansville'), ('milwaukee', 'Milwaukee'), ('des_moines', 'Des Moines'), ('wichita', 'Wichita'), ('pittsburgh', 'Pittsburgh'), ('iowa_city', 'Iowa City'), ('detroit', 'Detroit'), ('dayton', 'Dayton'), ('cleveland', 'Cleveland'), ('cincinnati', 'Cincinnati'), ('saskatoon', 'Saskatoon'), ('montreal', 'Montreal'), ('edmonton', 'Edmonton'), ('fort_mcmurray', 'Fort Mcmurray'), ('scarborough', 'Scarborough'), ('regina', 'Regina'), ('winnipeg', 'Winnipeg'), ('toronto', 'Toronto'), ('calgary', 'Calgary'), ('ottawa', 'Ottawa'), ('vancouver', 'Vancouver'), ('red_deer', 'Red Deer'), ('cambridge', 'Cambridge'), ('windsor', 'Windsor'), ('brandon', 'Brandon')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_2', 'Group 2'), ('group_1', 'Group 1'), ('group_3', 'Group 3'), ('group_0', 'Group 0'), ('kishore/kishori', 'Kishore/Kishori')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('southwest', 'Southwest'), ('midwest', 'Midwest'), ('canada', 'Canada'), ('west', 'West'), ('southeast', 'Southeast'), ('northeast', 'Northeast')], max_length=60, null=True),
        ),
    ]
