# Generated by Django 3.1.4 on 2021-01-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210116_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('hilltop', 'Hilltop'), ('harrisburg', 'Harrisburg'), ('warrington', 'Warrington'), ('cherry_hill', 'Cherry Hill'), ('downingtown', 'Downingtown'), ('edison', 'Edison'), ('northern_virginia', 'Northern Virginia'), ('parsippany', 'Parsippany'), ('richmond', 'Richmond'), ('albany_ny', 'Albany Ny'), ('syracuse', 'Syracuse'), ('clifton', 'Clifton'), ('westborough', 'Westborough'), ('virginia_beach', 'Virginia Beach'), ('delaware', 'Delaware'), ('westchester', 'Westchester'), ('lansdale', 'Lansdale'), ('philadelphia', 'Philadelphia'), ('hartford', 'Hartford'), ('springfield', 'Springfield'), ('allentown', 'Allentown'), ('long_island', 'Long Island'), ('scranton', 'Scranton'), ('robbinsville', 'Robbinsville'), ('boston', 'Boston'), ('atlantic_city', 'Atlantic City'), ('new_york', 'New York'), ('south_boston', 'South Boston'), ('washington_dc', 'Washington Dc'), ('jersey_city', 'Jersey City'), ('new_haven', 'New Haven'), ('roanoke', 'Roanoke'), ('atlanta', 'Atlanta'), ('columbia_sc', 'Columbia Sc'), ('albany_ga', 'Albany Ga'), ('charlotte', 'Charlotte'), ('knoxville', 'Knoxville'), ('gainesville', 'Gainesville'), ('perry', 'Perry'), ('raleigh', 'Raleigh'), ('chattanooga', 'Chattanooga'), ('greensboro', 'Greensboro'), ('greenville', 'Greenville'), ('huntsville', 'Huntsville'), ('melbourne', 'Melbourne'), ('columbia_tn', 'Columbia Tn'), ('calhoun', 'Calhoun'), ('mobile', 'Mobile'), ('birmingham', 'Birmingham'), ('augusta', 'Augusta'), ('orlando', 'Orlando'), ('tampa', 'Tampa'), ('memphis', 'Memphis'), ('orangeburg', 'Orangeburg'), ('nashville', 'Nashville'), ('dothan', 'Dothan'), ('miami', 'Miami'), ('myrtle_beach', 'Myrtle Beach'), ('montgomery', 'Montgomery'), ('savannah', 'Savannah'), ('florence', 'Florence'), ('jacksonville', 'Jacksonville'), ('midland', 'Midland'), ('new_orleans', 'New Orleans'), ('denver', 'Denver'), ('little_rock', 'Little Rock'), ('clear_lake', 'Clear Lake'), ('houston', 'Houston'), ('jackson', 'Jackson'), ('oklahoma_city', 'Oklahoma City'), ('dallas', 'Dallas'), ('beaumont', 'Beaumont'), ('lubbock', 'Lubbock'), ('corpus_christi', 'Corpus Christi'), ('austin', 'Austin'), ('panama', 'Panama'), ('san_antonio', 'San Antonio'), ('fresno', 'Fresno'), ('san_francisco', 'San Francisco'), ('san_diego', 'San Diego'), ('tucson', 'Tucson'), ('salt_lake_city', 'Salt Lake City'), ('bakersfield', 'Bakersfield'), ('phoenix', 'Phoenix'), ('seattle', 'Seattle'), ('san_jose', 'San Jose'), ('los_angeles', 'Los Angeles'), ('sacramento', 'Sacramento'), ('portland', 'Portland'), ('crystal_lake', 'Crystal Lake'), ('milwaukee', 'Milwaukee'), ('chicago', 'Chicago'), ('minneapolis', 'Minneapolis'), ('detroit', 'Detroit'), ('des_moines', 'Des Moines'), ('dayton', 'Dayton'), ('columbus', 'Columbus'), ('kansas_city', 'Kansas City'), ('sterling_heights', 'Sterling Heights'), ('wichita', 'Wichita'), ('cincinnati', 'Cincinnati'), ('lexington', 'Lexington'), ('st_louis', 'St Louis'), ('indianapolis', 'Indianapolis'), ('cleveland', 'Cleveland'), ('pittsburgh', 'Pittsburgh'), ('bloomington', 'Bloomington'), ('kalamazoo', 'Kalamazoo'), ('evansville', 'Evansville'), ('louisville', 'Louisville'), ('iowa_city', 'Iowa City'), ('munster', 'Munster'), ('brandon', 'Brandon'), ('saskatoon', 'Saskatoon'), ('vancouver', 'Vancouver'), ('winnipeg', 'Winnipeg'), ('red_deer', 'Red Deer'), ('fort_mcmurray', 'Fort Mcmurray'), ('ottawa', 'Ottawa'), ('regina', 'Regina'), ('toronto', 'Toronto'), ('montreal', 'Montreal'), ('edmonton', 'Edmonton'), ('windsor', 'Windsor'), ('cambridge', 'Cambridge'), ('calgary', 'Calgary'), ('scarborough', 'Scarborough')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_0', 'Group 0'), ('group_2', 'Group 2'), ('kishore/kishori', 'Kishore/Kishori'), ('group_3', 'Group 3'), ('group_1', 'Group 1')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('canada', 'Canada'), ('midwest', 'Midwest'), ('northeast', 'Northeast'), ('southwest', 'Southwest'), ('southeast', 'Southeast'), ('west', 'West')], max_length=60, null=True),
        ),
    ]
