# Generated by Django 3.1.5 on 2021-01-19 01:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20210116_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('clifton', 'Clifton'), ('lansdale', 'Lansdale'), ('philadelphia', 'Philadelphia'), ('boston', 'Boston'), ('new_york', 'New York'), ('jersey_city', 'Jersey City'), ('northern_virginia', 'Northern Virginia'), ('warrington', 'Warrington'), ('south_boston', 'South Boston'), ('hartford', 'Hartford'), ('scranton', 'Scranton'), ('cherry_hill', 'Cherry Hill'), ('new_haven', 'New Haven'), ('springfield', 'Springfield'), ('downingtown', 'Downingtown'), ('allentown', 'Allentown'), ('edison', 'Edison'), ('atlantic_city', 'Atlantic City'), ('hilltop', 'Hilltop'), ('westchester', 'Westchester'), ('virginia_beach', 'Virginia Beach'), ('albany_ny', 'Albany NY'), ('harrisburg', 'Harrisburg'), ('robbinsville', 'Robbinsville'), ('westborough', 'Westborough'), ('delaware', 'Delaware'), ('long_island', 'Long Island'), ('richmond', 'Richmond'), ('syracuse', 'Syracuse'), ('washington_dc', 'Washington DC'), ('parsippany', 'Parsippany'), ('roanoke', 'Roanoke'), ('jacksonville', 'Jacksonville'), ('chattanooga', 'Chattanooga'), ('columbia_sc', 'Columbia SC'), ('atlanta', 'Atlanta'), ('orangeburg', 'Orangeburg'), ('greensboro', 'Greensboro'), ('montgomery', 'Montgomery'), ('gainesville', 'Gainesville'), ('dothan', 'Dothan'), ('charlotte', 'Charlotte'), ('raleigh', 'Raleigh'), ('albany_ga', 'Albany GA'), ('birmingham', 'Birmingham'), ('melbourne', 'Melbourne'), ('greenville', 'Greenville'), ('knoxville', 'Knoxville'), ('orlando', 'Orlando'), ('perry', 'Perry'), ('calhoun', 'Calhoun'), ('huntsville', 'Huntsville'), ('savannah', 'Savannah'), ('augusta', 'Augusta'), ('memphis', 'Memphis'), ('florence', 'Florence'), ('nashville', 'Nashville'), ('miami', 'Miami'), ('myrtle_beach', 'Myrtle Beach'), ('mobile', 'Mobile'), ('columbia_tn', 'Columbia TN'), ('tampa', 'Tampa'), ('panama', 'Panama'), ('clear_lake', 'Clear Lake'), ('dallas', 'Dallas'), ('jackson', 'Jackson'), ('corpus_christi', 'Corpus Christi'), ('beaumont', 'Beaumont'), ('austin', 'Austin'), ('houston', 'Houston'), ('oklahoma_city', 'Oklahoma City'), ('lubbock', 'Lubbock'), ('new_orleans', 'New Orleans'), ('san_antonio', 'San Antonio'), ('denver', 'Denver'), ('midland', 'Midland'), ('little_rock', 'Little Rock'), ('san_jose', 'San Jose'), ('salt_lake_city', 'Salt Lake'), ('bakersfield', 'Bakersfield'), ('seattle', 'Seattle'), ('portland', 'Portland'), ('phoenix', 'Phoenix'), ('fresno', 'Fresno'), ('los_angeles', 'Los Angeles'), ('san_francisco', 'San Francisco'), ('san_diego', 'San Diego'), ('sacramento', 'Sacramento'), ('tucson', 'Tucson'), ('evansville', 'Evansville'), ('cincinnati', 'Cincinnati'), ('kalamazoo', 'Kalamazoo'), ('wichita', 'Wichita'), ('crystal_lake', 'Crystal Lake'), ('indianapolis', 'Indianapolis'), ('chicago', 'Chicago'), ('dayton', 'Dayton'), ('louisville', 'Louisville'), ('des_moines', 'Des Moines'), ('minneapolis', 'Minneapolis'), ('cleveland', 'Cleveland'), ('kansas_city', 'Kansas City'), ('detroit', 'Detroit'), ('columbus', 'Columbus'), ('lexington', 'Lexington'), ('pittsburgh', 'Pittsburgh'), ('munster', 'Munster'), ('sterling_heights', 'Sterling Heights'), ('bloomington', 'Bloomington'), ('milwaukee', 'Milwaukee'), ('iowa_city', 'Iowa City'), ('st_louis', 'St Louis'), ('cambridge', 'Cambridge'), ('scarborough', 'Scarborough'), ('vancouver', 'Vancouver'), ('ottawa', 'Ottawa'), ('calgary', 'Calgary'), ('winnipeg', 'Winnipeg'), ('brandon', 'Brandon'), ('red_deer', 'Red Deer'), ('regina', 'Regina'), ('toronto', 'Toronto'), ('windsor', 'Windsor'), ('montreal', 'Montreal'), ('saskatoon', 'Saskatoon'), ('edmonton', 'Edmonton'), ('fort_mcmurray', 'Fort Mcmurray')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('kishore/kishori', 'Kishore/Kishori'), ('group_1', 'Group 1'), ('group_3', 'Group 3'), ('group_2', 'Group 2'), ('group_0', 'Group 0')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('northeast', 'Northeast'), ('west', 'West'), ('midwest', 'Midwest'), ('southeast', 'Southeast'), ('southwest', 'Southwest'), ('canada', 'Canada')], max_length=60, null=True),
        ),
        migrations.CreateModel(
            name='ExternalUserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveBigIntegerField()),
                ('code_expiration', models.DateTimeField(default=datetime.datetime(2021, 1, 19, 20, 19, 36, 944593))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
