# Generated by Django 3.1.5 on 2021-01-22 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210118_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalusermodel',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 23, 18, 33, 15, 346147, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('allentown', 'Allentown'), ('syracuse', 'Syracuse'), ('new_haven', 'New Haven'), ('roanoke', 'Roanoke'), ('edison', 'Edison'), ('cherry_hill', 'Cherry Hill'), ('downingtown', 'Downingtown'), ('south_boston', 'South Boston'), ('westchester', 'Westchester'), ('albany_ny', 'Albany NY'), ('parsippany', 'Parsippany'), ('robbinsville', 'Robbinsville'), ('jersey_city', 'Jersey City'), ('hilltop', 'Hilltop'), ('hartford', 'Hartford'), ('washington_dc', 'Washington DC'), ('atlantic_city', 'Atlantic City'), ('northern_virginia', 'Northern Virginia'), ('springfield', 'Springfield'), ('virginia_beach', 'Virginia Beach'), ('boston', 'Boston'), ('long_island', 'Long Island'), ('lansdale', 'Lansdale'), ('westborough', 'Westborough'), ('philadelphia', 'Philadelphia'), ('harrisburg', 'Harrisburg'), ('warrington', 'Warrington'), ('delaware', 'Delaware'), ('richmond', 'Richmond'), ('scranton', 'Scranton'), ('clifton', 'Clifton'), ('new_york', 'New York'), ('calhoun', 'Calhoun'), ('jacksonville', 'Jacksonville'), ('greenville', 'Greenville'), ('raleigh', 'Raleigh'), ('birmingham', 'Birmingham'), ('melbourne', 'Melbourne'), ('perry', 'Perry'), ('mobile', 'Mobile'), ('huntsville', 'Huntsville'), ('augusta', 'Augusta'), ('myrtle_beach', 'Myrtle Beach'), ('knoxville', 'Knoxville'), ('albany_ga', 'Albany GA'), ('tampa', 'Tampa'), ('savannah', 'Savannah'), ('orangeburg', 'Orangeburg'), ('dothan', 'Dothan'), ('greensboro', 'Greensboro'), ('columbia_tn', 'Columbia TN'), ('nashville', 'Nashville'), ('gainesville', 'Gainesville'), ('chattanooga', 'Chattanooga'), ('miami', 'Miami'), ('montgomery', 'Montgomery'), ('memphis', 'Memphis'), ('florence', 'Florence'), ('orlando', 'Orlando'), ('columbia_sc', 'Columbia SC'), ('atlanta', 'Atlanta'), ('charlotte', 'Charlotte'), ('oklahoma_city', 'Oklahoma City'), ('denver', 'Denver'), ('new_orleans', 'New Orleans'), ('corpus_christi', 'Corpus Christi'), ('lubbock', 'Lubbock'), ('clear_lake', 'Clear Lake'), ('jackson', 'Jackson'), ('houston', 'Houston'), ('midland', 'Midland'), ('dallas', 'Dallas'), ('beaumont', 'Beaumont'), ('san_antonio', 'San Antonio'), ('austin', 'Austin'), ('little_rock', 'Little Rock'), ('panama', 'Panama'), ('phoenix', 'Phoenix'), ('san_francisco', 'San Francisco'), ('san_diego', 'San Diego'), ('san_jose', 'San Jose'), ('seattle', 'Seattle'), ('sacramento', 'Sacramento'), ('los_angeles', 'Los Angeles'), ('tucson', 'Tucson'), ('salt_lake_city', 'Salt Lake'), ('portland', 'Portland'), ('fresno', 'Fresno'), ('bakersfield', 'Bakersfield'), ('kansas_city', 'Kansas City'), ('indianapolis', 'Indianapolis'), ('sterling_heights', 'Sterling Heights'), ('evansville', 'Evansville'), ('louisville', 'Louisville'), ('munster', 'Munster'), ('detroit', 'Detroit'), ('minneapolis', 'Minneapolis'), ('iowa_city', 'Iowa City'), ('pittsburgh', 'Pittsburgh'), ('st_louis', 'St Louis'), ('kalamazoo', 'Kalamazoo'), ('chicago', 'Chicago'), ('des_moines', 'Des Moines'), ('cleveland', 'Cleveland'), ('cincinnati', 'Cincinnati'), ('wichita', 'Wichita'), ('crystal_lake', 'Crystal Lake'), ('dayton', 'Dayton'), ('lexington', 'Lexington'), ('bloomington', 'Bloomington'), ('milwaukee', 'Milwaukee'), ('columbus', 'Columbus'), ('ottawa', 'Ottawa'), ('red_deer', 'Red Deer'), ('vancouver', 'Vancouver'), ('calgary', 'Calgary'), ('windsor', 'Windsor'), ('scarborough', 'Scarborough'), ('brandon', 'Brandon'), ('montreal', 'Montreal'), ('fort_mcmurray', 'Fort Mcmurray'), ('toronto', 'Toronto'), ('saskatoon', 'Saskatoon'), ('edmonton', 'Edmonton'), ('regina', 'Regina'), ('cambridge', 'Cambridge'), ('winnipeg', 'Winnipeg')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_2', 'Group 2'), ('kishore/kishori', 'Kishore/Kishori'), ('group_1', 'Group 1'), ('group_3', 'Group 3'), ('group_0', 'Group 0')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('southeast', 'Southeast'), ('southwest', 'Southwest'), ('midwest', 'Midwest'), ('west', 'West'), ('canada', 'Canada'), ('northeast', 'Northeast')], max_length=60, null=True),
        ),
    ]
