# Generated by Django 3.1.4 on 2021-02-04 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20210122_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='mukhpathitem',
            name='sanskrit_audio_url',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='mukhpathitem',
            name='sanskrit_lipi_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalusermodel',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 5, 18, 32, 40, 635921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('lansdale', 'Lansdale'), ('new_haven', 'New Haven'), ('westborough', 'Westborough'), ('boston', 'Boston'), ('atlantic_city', 'Atlantic City'), ('edison', 'Edison'), ('warrington', 'Warrington'), ('philadelphia', 'Philadelphia'), ('scranton', 'Scranton'), ('springfield', 'Springfield'), ('long_island', 'Long Island'), ('washington_dc', 'Washington DC'), ('hartford', 'Hartford'), ('northern_virginia', 'Northern Virginia'), ('harrisburg', 'Harrisburg'), ('delaware', 'Delaware'), ('clifton', 'Clifton'), ('robbinsville', 'Robbinsville'), ('south_boston', 'South Boston'), ('richmond', 'Richmond'), ('new_york', 'New York'), ('virginia_beach', 'Virginia Beach'), ('downingtown', 'Downingtown'), ('albany_ny', 'Albany NY'), ('roanoke', 'Roanoke'), ('jersey_city', 'Jersey City'), ('allentown', 'Allentown'), ('cherry_hill', 'Cherry Hill'), ('syracuse', 'Syracuse'), ('westchester', 'Westchester'), ('hilltop', 'Hilltop'), ('parsippany', 'Parsippany'), ('tampa', 'Tampa'), ('calhoun', 'Calhoun'), ('nashville', 'Nashville'), ('atlanta', 'Atlanta'), ('charlotte', 'Charlotte'), ('raleigh', 'Raleigh'), ('perry', 'Perry'), ('knoxville', 'Knoxville'), ('mobile', 'Mobile'), ('florence', 'Florence'), ('birmingham', 'Birmingham'), ('dothan', 'Dothan'), ('orlando', 'Orlando'), ('albany_ga', 'Albany GA'), ('savannah', 'Savannah'), ('huntsville', 'Huntsville'), ('greensboro', 'Greensboro'), ('chattanooga', 'Chattanooga'), ('orangeburg', 'Orangeburg'), ('montgomery', 'Montgomery'), ('greenville', 'Greenville'), ('columbia_tn', 'Columbia TN'), ('gainesville', 'Gainesville'), ('augusta', 'Augusta'), ('columbia_sc', 'Columbia SC'), ('myrtle_beach', 'Myrtle Beach'), ('memphis', 'Memphis'), ('jacksonville', 'Jacksonville'), ('miami', 'Miami'), ('melbourne', 'Melbourne'), ('new_orleans', 'New Orleans'), ('austin', 'Austin'), ('jackson', 'Jackson'), ('midland', 'Midland'), ('clear_lake', 'Clear Lake'), ('panama', 'Panama'), ('little_rock', 'Little Rock'), ('dallas', 'Dallas'), ('denver', 'Denver'), ('lubbock', 'Lubbock'), ('oklahoma_city', 'Oklahoma City'), ('corpus_christi', 'Corpus Christi'), ('san_antonio', 'San Antonio'), ('beaumont', 'Beaumont'), ('houston', 'Houston'), ('los_angeles', 'Los Angeles'), ('bakersfield', 'Bakersfield'), ('phoenix', 'Phoenix'), ('salt_lake_city', 'Salt Lake'), ('san_jose', 'San Jose'), ('fresno', 'Fresno'), ('sacramento', 'Sacramento'), ('san_francisco', 'San Francisco'), ('tucson', 'Tucson'), ('san_diego', 'San Diego'), ('seattle', 'Seattle'), ('portland', 'Portland'), ('cleveland', 'Cleveland'), ('crystal_lake', 'Crystal Lake'), ('kalamazoo', 'Kalamazoo'), ('pittsburgh', 'Pittsburgh'), ('dayton', 'Dayton'), ('evansville', 'Evansville'), ('des_moines', 'Des Moines'), ('iowa_city', 'Iowa City'), ('st_louis', 'St Louis'), ('bloomington', 'Bloomington'), ('columbus', 'Columbus'), ('lexington', 'Lexington'), ('louisville', 'Louisville'), ('cincinnati', 'Cincinnati'), ('detroit', 'Detroit'), ('indianapolis', 'Indianapolis'), ('chicago', 'Chicago'), ('minneapolis', 'Minneapolis'), ('munster', 'Munster'), ('kansas_city', 'Kansas City'), ('milwaukee', 'Milwaukee'), ('wichita', 'Wichita'), ('sterling_heights', 'Sterling Heights'), ('fort_mcmurray', 'Fort Mcmurray'), ('red_deer', 'Red Deer'), ('regina', 'Regina'), ('ottawa', 'Ottawa'), ('montreal', 'Montreal'), ('toronto', 'Toronto'), ('windsor', 'Windsor'), ('winnipeg', 'Winnipeg'), ('cambridge', 'Cambridge'), ('saskatoon', 'Saskatoon'), ('scarborough', 'Scarborough'), ('edmonton', 'Edmonton'), ('vancouver', 'Vancouver'), ('brandon', 'Brandon'), ('calgary', 'Calgary')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_0', 'Group 0'), ('group_1', 'Group 1'), ('kishore/kishori', 'Kishore/Kishori'), ('group_2', 'Group 2'), ('group_3', 'Group 3')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('northeast', 'Northeast'), ('southeast', 'Southeast'), ('west', 'West'), ('canada', 'Canada'), ('midwest', 'Midwest'), ('southwest', 'Southwest')], max_length=60, null=True),
        ),
    ]
