# Generated by Django 3.1.4 on 2021-03-29 21:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210204_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bkms_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='externalusermodel',
            name='code_expiration',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 30, 21, 31, 58, 80191, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='center',
            field=models.CharField(choices=[('westchester', 'Westchester'), ('warrington', 'Warrington'), ('delaware', 'Delaware'), ('south_boston', 'South Boston'), ('washington_dc', 'Washington DC'), ('edison', 'Edison'), ('robbinsville', 'Robbinsville'), ('new_haven', 'New Haven'), ('parsippany', 'Parsippany'), ('atlantic_city', 'Atlantic City'), ('new_york', 'New York'), ('lansdale', 'Lansdale'), ('clifton', 'Clifton'), ('richmond', 'Richmond'), ('jersey_city', 'Jersey City'), ('allentown', 'Allentown'), ('hartford', 'Hartford'), ('northern_virginia', 'Northern Virginia'), ('philadelphia', 'Philadelphia'), ('roanoke', 'Roanoke'), ('scranton', 'Scranton'), ('syracuse', 'Syracuse'), ('harrisburg', 'Harrisburg'), ('downingtown', 'Downingtown'), ('springfield', 'Springfield'), ('virginia_beach', 'Virginia Beach'), ('boston', 'Boston'), ('westborough', 'Westborough'), ('hilltop', 'Hilltop'), ('cherry_hill', 'Cherry Hill'), ('albany_ny', 'Albany NY'), ('long_island', 'Long Island'), ('gainesville', 'Gainesville'), ('chattanooga', 'Chattanooga'), ('columbia_sc', 'Columbia SC'), ('columbia_tn', 'Columbia TN'), ('perry', 'Perry'), ('augusta', 'Augusta'), ('albany_ga', 'Albany GA'), ('orangeburg', 'Orangeburg'), ('savannah', 'Savannah'), ('huntsville', 'Huntsville'), ('calhoun', 'Calhoun'), ('charlotte', 'Charlotte'), ('knoxville', 'Knoxville'), ('birmingham', 'Birmingham'), ('greenville', 'Greenville'), ('jacksonville', 'Jacksonville'), ('nashville', 'Nashville'), ('raleigh', 'Raleigh'), ('greensboro', 'Greensboro'), ('miami', 'Miami'), ('atlanta', 'Atlanta'), ('dothan', 'Dothan'), ('florence', 'Florence'), ('myrtle_beach', 'Myrtle Beach'), ('montgomery', 'Montgomery'), ('mobile', 'Mobile'), ('tampa', 'Tampa'), ('orlando', 'Orlando'), ('memphis', 'Memphis'), ('melbourne', 'Melbourne'), ('new_orleans', 'New Orleans'), ('little_rock', 'Little Rock'), ('lubbock', 'Lubbock'), ('austin', 'Austin'), ('midland', 'Midland'), ('houston', 'Houston'), ('jackson', 'Jackson'), ('denver', 'Denver'), ('dallas', 'Dallas'), ('san_antonio', 'San Antonio'), ('clear_lake', 'Clear Lake'), ('beaumont', 'Beaumont'), ('panama', 'Panama'), ('oklahoma_city', 'Oklahoma City'), ('corpus_christi', 'Corpus Christi'), ('bakersfield', 'Bakersfield'), ('san_jose', 'San Jose'), ('los_angeles', 'Los Angeles'), ('san_diego', 'San Diego'), ('fresno', 'Fresno'), ('tucson', 'Tucson'), ('phoenix', 'Phoenix'), ('san_francisco', 'San Francisco'), ('seattle', 'Seattle'), ('salt_lake_city', 'Salt Lake'), ('portland', 'Portland'), ('sacramento', 'Sacramento'), ('iowa_city', 'Iowa City'), ('louisville', 'Louisville'), ('kansas_city', 'Kansas City'), ('detroit', 'Detroit'), ('munster', 'Munster'), ('columbus', 'Columbus'), ('indianapolis', 'Indianapolis'), ('dayton', 'Dayton'), ('minneapolis', 'Minneapolis'), ('kalamazoo', 'Kalamazoo'), ('st_louis', 'St Louis'), ('pittsburgh', 'Pittsburgh'), ('chicago', 'Chicago'), ('sterling_heights', 'Sterling Heights'), ('crystal_lake', 'Crystal Lake'), ('cleveland', 'Cleveland'), ('milwaukee', 'Milwaukee'), ('des_moines', 'Des Moines'), ('lexington', 'Lexington'), ('evansville', 'Evansville'), ('wichita', 'Wichita'), ('bloomington', 'Bloomington'), ('cincinnati', 'Cincinnati'), ('cambridge', 'Cambridge'), ('edmonton', 'Edmonton'), ('saskatoon', 'Saskatoon'), ('fort_mcmurray', 'Fort Mcmurray'), ('ottawa', 'Ottawa'), ('red_deer', 'Red Deer'), ('calgary', 'Calgary'), ('windsor', 'Windsor'), ('brandon', 'Brandon'), ('scarborough', 'Scarborough'), ('vancouver', 'Vancouver'), ('winnipeg', 'Winnipeg'), ('regina', 'Regina'), ('montreal', 'Montreal'), ('toronto', 'Toronto')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mandal',
            field=models.CharField(choices=[('group_1', 'Group 1'), ('group_0', 'Group 0'), ('group_2', 'Group 2'), ('kishore/kishori', 'Kishore/Kishori'), ('group_3', 'Group 3')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('northeast', 'Northeast'), ('canada', 'Canada'), ('midwest', 'Midwest'), ('southeast', 'Southeast'), ('west', 'West'), ('southwest', 'Southwest')], max_length=60, null=True),
        ),
    ]
